### ISSUE TITLE
Layout issue since moving from 1.1.4 to 1.2.0

### ISSUE THREAD

**Issue by u01jmg3** [apache/cordova-plugin-wkwebview-engine#105]
# Bug Report

### What is expected to happen?

On `1.1.4` when opening my Cordova/PhoneGap app on an iPad running iOS 12.3.1 the status bar is correctly displayed where its height is enough to show the clock, date, battery percentage, etc as it should.

### What does actually happen?

Since moving to `1.2.0` when opening my Cordova/PhoneGap app, the status bar is incorrectly displayed with a height almost double what it should be.

<img width="768" alt="comparison" src="https://user-images.githubusercontent.com/1266205/61126562-ad43bc00-a4a4-11e9-96ea-d11b131c46c6.png">

## Information

- I believe this code may be the culprit: https://github.com/apache/cordova-plugin-wkwebview-engine/commit/81eeadeb542fefc05c4cd5e68ba0221e6a965c73
  - CB-13987: (ios) Fix WKWebView doesn't layout properly at launch on iPhone X
- Can applying this new setting be overwritten?
- What about an iPad running iOS 11 or greater that doesn't require this iPhone X display change?

### Command or Code

N/A

### Environment, Platform, Device

iPad running iOS 12.3.1

### Version information

```
<plugin name="cordova-plugin-statusbar" spec="^2.4.3"/>
<plugin name="cordova-plugin-wkwebview-engine" spec="^1.2.0"/>
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by janpio** [comment]
ping @hector-romero who created the PR and @shazron who merged this.

**Comment by fuzzy990** [comment]
Once I updated my app to 1.2.0 on iPhone X, my app bled into the top safe area. Now it seems to ignore any CSS referencing safe-area-inset-top.

**Comment by u01jmg3** [comment]
- Reverting the commit I pointed to fixes the problem: https://github.com/apache/cordova-plugin-wkwebview-engine/compare/master...uofa:develop
- I realise the change is needed for the iPhone X - is there anyway it can be controlled so that on an iPad you can turn off applying the setting?

**Comment by janpio** [comment]
Acknowledged, PR reverting this at https://github.com/apache/cordova-plugin-wkwebview-engine/pull/107 It also has the correct solution to fix the original problem.

Will start a 1.2.1 release tomorrow, expect release next week (Apache release voting period).

**Comment by janpio** [comment]
Release 1.2.1 is now in voting (which will go a minimum of 48 hourse), if that succeeds I can do the official release to NPM.

**Comment by janpio** [comment]
1.2.1 has been released and can now be used in your apps.

**Comment by u01jmg3** [comment]
Appreciate the speedy release
