### ISSUE TITLE
WKWebView for cookie synchronization management, there is no perfect solution？

### ISSUE THREAD

**Issue by CrazyRoy** [apache/cordova-plugin-wkwebview-engine#106]
WKWebView for cookie synchronization management, there is no perfect solution ???

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support 😉 
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).
