### ISSUE TITLE
Content dimensions incorrect at startup on iPhone X

### ISSUE THREAD

**Issue by xtassin** [apache/cordova-plugin-wkwebview-engine#108]
As described in this original issue #53, the document body's first child is incorrectly sized when starting the application. The issue is gone after rotating the device and back to original orientation. The body dimensions appear to be always correct though. 
This only occurs on iPhone X and likes.

A fix for this issue, provided in #45, was recently reverted in #107

**Comment by dpogue** [comment]
1. What is the value of the `viewport` meta tag?
2. Is the body's first child element using `height: 100%` or `height: 100vh`?

The fix in #45 is not a fix because it takes control of the webview behaviour away from the app developer and unilaterally enforces a decision about the handling of safe areas on all Cordova apps. That change is already known to break several existing apps that are handling safe areas properly, which is why it was reverted.

**Comment by xtassin** [comment]
1. "width=device-width, height=device-height, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, viewport-fit=cover"
2. I tried with both % and vh with the same result

I understand #45 fix may not be a viable solution. However, I believe the sizing issue is most likely a bug and not a misuse of CSS or Markup.

Again, sizing is correct once device has been rotated or some other reflow event occurs (resize, etc.)

I fixed my app temporarily with a fork of #45 but I would love to see a proper solution that would fit everyone needs.

Thank you.

**Comment by jacobweber** [comment]
Doesn't #45 give **more** control to the app developer, by letting them manage the insets using CSS, instead of adding them automatically? I suppose it could be configurable though.

**Comment by dpogue** [comment]
It is not the job of Cordova to make those decisions. It is up to the app developer to say what they want with their `viewport-fit` meta tag.

**Comment by dominic-simplan** [comment]
@xtassin I had the same issue as you're describing. It was a bit trial-and-error with the height settings, but I think [this example repository](https://github.com/dominic-simplan/wkwebview) should demonstrate a working setup. If not, maybe you can modify it and show your issue?

**Comment by xtassin** [comment]
Hi Dominic,

I am sorry but I can't get the expected result when running your example.

I built it with PhoneGap Build and ran it in app-live.browserstack.com

As you can see from the screenshot, the viewport does not extend to the full iPhone screen size.

It seems like the splashscreen image is ignored.

![image](https://user-images.githubusercontent.com/296572/62409301-29797d00-b5d5-11e9-8164-310a1539905e.png)

Did I miss something?

**Comment by dominic-simplan** [comment]
@xtassin sorry, no idea, I am running it directly on a Mac in a simulator:
![grafik](https://user-images.githubusercontent.com/22240239/62441409-48524d80-b754-11e9-9c31-93ac2476ee7b.png)

Can you see [the splashscreen](https://github.com/dominic-simplan/wkwebview/blob/master/res/screen/ios/Default%402x%7Euniversal%7Eanyany.png) during startup? The splashscreen is defined in the [config.xml](https://github.com/dominic-simplan/wkwebview/blob/master/config.xml#L30), but maybe something is wrong with the definition?

**Comment by onaluf** [comment]
I've got the exact same issue as @xtassin (fine after rotate) and the fix from @deedw fixes it

**Comment by onaluf** [comment]
@dpogue Yes `100vh` does work if I set it on an element on the page. Doesn't change anything if I directly apply it to `html` or `body` though

**Comment by deedw** [comment]
I ended up having to fork and reapply the fix from #45 to get it working reliably.

**Comment by dominic-simplan** [comment]
@onaluf @deedw Here is an [example repository](https://github.com/dominic-simplan/wkwebview) which shows the correct behavior in the iOS simulator. Does this not work for you? Or otherwise, can you provide a simple repository which demonstrates your issue?

**Comment by onaluf** [comment]
Hi @dominic-simplan, yes the example work. This version doesn't though: https://github.com/onaluf/wkwebview . What I did there is: 
- remove the padding that used the safe area inset
- made the container position absolutely

With those two changes the page will behave like @xtassin described: the container will only fill the screen partially until the device is rotated, which to me is where the bug **really** is. Even if the behaviour we want **is** having the container not take the full screen it shouldn't change once you rotate the device...  

On a side note with `height: 100vh` the issue disappear.

**Comment by meishier** [comment]
hi, @onaluf, 

> On a side note with height: 100vh the issue disappear.

I git clone your https://github.com/onaluf/wkwebview , the issue does not disappear.  After app boots, it still only fill the screen partially.

**Comment by onaluf** [comment]
@meishier did you set the height on the container div? It doesn’t work if you set it to the body/html element

**Comment by meishier** [comment]
@onaluf, thank you very much

html/body 100%
#container 100%,  not works

html/body 100%
#container 100vh,  works

**Comment by spinninghamster** [comment]
It's working for me fine in the Mac simulator without the 100vh. Am I affected by this bug in real devices? Or am I fine if it works for me in the simulator?

It would appear this only happens if the container is `position: absolute;`?

**Comment by jacobweber** [comment]
So far the suggested fix is working for me. I already had `viewport-fit=cover` and head/body at 100% x 100%. I changed the first visible child element of body from 100% x 100% to 100vw x 100vh, and I'm no longer seeing the extra margin.

I'm wondering how reliable this is, e.g. if additional child elements of body are added with 100% instead of 100vw, will that re-introduce the margin? Or is it only calculated when the app launches?

BTW, the issue never appeared every time -- I would usually need to re-launch it a few times for it to appear.

**Comment by jespertheend** [comment]
@spinninghamster I think you're fine on real devices if it works in the simulator. I'm running my app in the simulator and I am actually seeing a huge white border at the bottom. 
![image](https://user-images.githubusercontent.com/2737650/65975434-e7eb3e00-e46e-11e9-9b21-27d1766f3f14.png)

@dpogue using height: 100vh on the body does make the body full height, but unfortunately window.innerHeight still reports the incorrect height. So a lot of my UI, including my full screen canvas, gets scaled/positioned incorrectly. I get that the fix in #45 is not a clean solution and breaks existing apps. But it would it be possible to still have this functionality using a preference in cordovas config.xml for example?

**Comment by dpogue** [comment]
@jespertheend Are you setting `viewport-fit=cover` in your meta `viewport` tag?

**Comment by jespertheend** [comment]
@dpogue yes

**Comment by jespertheend** [comment]
Hmm I'm actually gettin the correct value from `window.innerHeight` now. I'll do some more investigating...

**Comment by jespertheend** [comment]
@dpogue ah I see, I was running a different emulator which had a different screen size. That got me confused for a bit. Yeah it does seem to report the wrong height: 818 (on 11 Pro Max) and when I rotate the device and rotate it back, it reports (896). On iPhone X it's 734 and 812 respectively.

**Comment by lovelyelfpop** [comment]
Make `UIScrollViewContentInsetAdjustmentNever` be a configuration would be nice.

**Comment by dpogue** [comment]
@lovelyelfpop It *is* configurable, via your page, using `viewport-fit=cover`. That causes WKWebView to apply UIScrollViewContentInsetAdjustmentNever to the webview.

**Comment by lovelyelfpop** [comment]
@dpogue I already use `viewport-fit=cover`, but still seeing a blank area at the bottom

**Comment by dolin-tan** [comment]
@dominic-simplan meishier  Hi, man, I'm facing this problem. Is there a unified way to solve it?

**Comment by Pigsnuck** [comment]
Not sure why this was closed, because it's still an issue.

**Comment by DuBistKomisch** [comment]
we've also forked with the fix from #45

```
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no, viewport-fit=cover">
```

we've had `viewport-fit=cover` the entire time so clearly doesn't do the same thing initially

**Comment by wytlytningNZ** [comment]
Like @DuBistKomisch, we have also forked with the fix from #45 and have had `viewport-fit=cover` the entire time

**Comment by jacobweber** [comment]
@DuBistKomisch @wytlytningNZ Did you guys try the suggested fix, setting the first visible child element of body to `width: 100vw; height: 100vh`, along with `viewport-fit=cover`?

**Comment by xtassin** [comment]
@jacobweber this solution personally never satisfied me. We are talking about a web browser and HTML specs do not require a top container. My app does not have one and I don't like to have to add one in order to make this work **specifically** on iPhoneX. It is more like a hack (think IE5, 1999) and this is why people keep coming to this thread to find a solution to a non standard problem.

**Comment by dpogue** [comment]
I will say again that this is **not** a Cordova bug. If you are seeing problems then it's related to your HTML content and the meta tags and stylings in your content.

**Comment by jacobweber** [comment]
I would suggest at least adding this info to the documentation -- the 100vw thing is, as far as I know, not related to any standard.

**Comment by DuBistKomisch** [comment]
the fact that the height changes before and after rotating means to me that this is clearly an underlying bug, if not in cordova than iOS itself. I also have an issue where the window `innerWidth` and `innerHeight` are reported as both the same in the window `'resize'` event listener (workaround is to `setTimeout(100)` derp), so there seems to be some race issue with the window size in general?

I will try the `100vh` workaround as soon as I have a chance, but that still doesn't fix `window.innerHeight` reporting the wrong value, I guess we need to read the real width/height of the body tag or something?

:+1: to exposing a cordova preference to work around this bug

**Comment by Pigsnuck** [comment]
I will share my solution for all those other frustrated developers.  I was fiddling around with this issue for quite some time also.  I experienced the issues with WkWebkit here too, but the following steps resolved all issues for me.  The main thing to note is that upgrading my project DID NOT WORK.  I had to completely rebuild it.  I'm not sure which file change made the difference, but 

- Ran` cordova plugin ls` and saved the results.
- Removed all cordova platforms (`cordova platform rm ios`, etc).
- Deleted the /plugins folder.
- Updated cordova to the latest version (just to be sure - it was already the latest for me).
- Reinstalled all platforms.
- Reinstalled all plugins (especially cordova-plugin-webkit and the localserver plugins to use http://localhost:8080).
- Applied the viewport meta-tag.

After these steps, everything ran full-screen correctly without any bugs. Like any good developer, I immediately checked everything into source control.

Then I copied my Images.xcassets file containing my logos and screenshots over to the /platforms/ios directory.  After that, I started experiencing all the problems above again.  I had to rebuild this file manually.

**Comment by peterfox1** [comment]
Just to add in case anyone is still getting this & finds this issue - I found that the following style can cause the gap to remain even when you have the viewport set + 100vw/vh.
```
html {
	position: fixed;
}
```
If you happen to have this style set, you may need to remove it.

**Comment by brodybits** [comment]
We maintainers do not have the resources to actively support closed issues. I suggest raising a documentation issue here: <https://github.com/apache/cordova-docs/issues>

**Comment by louisameline** [comment]
> We maintainers do not have the resources to actively support closed issues

Please reopen the issue. Or please explain how on Earth I can have in the console:
- at page load, `window.innerHeight` returns 734
- after a rotation to landscape and back to portrait, `window.innerHeight` returns 812

734 = 812 (actual screen height) - 44 (top safe area inset) - 34 (bottom safe area inset).
So, I'm not Einstein but I'd say that **at page load and until rotated, the window.innerHeight wrongfully subtracts the safe area insets**.

I will also add that the issue happens ONLY if the content of page is smaller in height than the window height. Exemple: if the "natural height" of my page is 500, `window.innerHeight` returns 734 as I said. If my page content is 750px high, `window.innerHeight` will return 750, and if my page content overflows the window, `window.innerHeight` will return 812.

Also, **the Ionic-maintained WKWebView fork doesn't have this bug, my guess is that they must have seen it and fixed it**. Maybe their fix can be cherry picked?

Also, as others, I think that the 100vh 100% stuff is insufficient. No one should be forced to code like this. A bug fix is better than a poor hackish workaround. And it didn't even work for me, although I didn't insist too much to be honest.

Until this bug is acknowledged and fixed, let me share a temporary workaround I found:
```javascript
const style = document.querySelector('#someContentElement').style
style.minHeight = '1000px'

setTimeout(() => {
	document.body.style.display = 'contents'
	style.minHeight = ''
}, 0)
```
The idea is simple: make the content overflow the window, switch the body display to `contents` and then remove the content overflow. This will make `window.innerHeight` return the correct value.

Caveat due to `display: contents;`: the padding and margin of the body, if any, will not be enforced anymore, you'll have to set it on children elements instead. Also, a background set on the body will not work anymore, but you can set it on the html tag instead. Finally, your page will lose accessibility (for visually impaired people and such). 

I'm using iPhone XS, iOS 13.4, Xcode 11.4, cordova-ios 5.1.1, cordova-plugin-wkwebview-engine 1.2.1, `viewport-fit=cover`.

**Comment by louisameline** [comment]
@dpogue and any other Cordova maintainer: I can easily share a project to replicate the issue. A blank Quasar project is actually enough to demonstrate the issue (Quasar is a Vue framework that lets you builds apps super easily for many platforms). Or can you please confirm that Cordova cannot possibly be responsible for what I explained and that I should open a ticket in the Webkit bug tracker instead? Thank you

**Comment by fmiguelroliveira** [comment]
I've tried all the possible fixes and no one works. I'm still having wrong height dimensions.

In my project i don't have any container. I'm working with display blocks inside html/body.

BTW is there a probably solution like triggering the rotation just to fix dimensions?

This is just annoying...we should not have to care about this kind of issues, that takes us time and money...

**Comment by louisameline** [comment]
For something so basic, yeah... and Ionic fixed it... If everyone in this thread follows the webkit bug report, it might help it get attention.

**Comment by xtassin** [comment]
I would humbly propose to [use a fork I made some time ago](https://github.com/xtassin/cordova-plugin-wkwebview-engine). It's not really fresh but it includes the (imperfect) fix #45 to solve this problem. I will state it again: in my opinion, a specific CSS trick is not the answer to a rendering bug. I follow the webkit bug report.

**Comment by fmiguelroliveira** [comment]
Dear Felllows,

This is soooo stupid (not my fix, but the whole process)...

I solved the problem using document.body.offsetHeight.

After an enormous text alert created with all kind of document heights i found out that the wkview only returns the real size with the offsetheight...

hope this helps anyone, at least the ones who doesn't have a container inside body.

Nevertheless i'll keep my attention on bugtracking where i subscribed for news.

Saúde,
Miguel

**Comment by louisameline** [comment]
Body offset height won't work when your content is smaller than the window height. And there can be dependencies that use window.innerHeight, so in my case I really had to "fix" innerHeight with the 100vh trick. Otherwise I would have used a fork of Cordova as suggested by @xtassin

**Comment by fmiguelroliveira** [comment]
This is my css parameters:

`html, body {
    height: 100vh;
    min-height: 100vh;
}

html {
    position: relative;
}

body {
    margin: 0;
    padding: 0;
    overflow-x: hidden;
}`

**Comment by obxyann** [comment]
Confirm xtassin and louisameline's comment set viewport-fit=cover and height: 100vh only worked at startup but later when I use to compute the **window height** to program my layout dynamically it still go wrong. xtassin's  comment can solve this problem.

**Comment by yellaiahd** [comment]
install cordova plugin add cordova-plugin-statusbar   (check api for more information cordova-plugin-statusbar)  and add below preferences
<preference name="StatusBarOverlaysWebView" value="false"/>
  <preference name="StatusBarBackgroundColor" value="#000000"/>
  <preference name="StatusBarStyle" value="lightcontent"/>

**Comment by Pietfro** [comment]
For anyone that is still struggling with the viewport sizing on iOS, here is the most bulletproof solution I came up with:
```
html,
body {
    height: calc(100vh - env(safe-area-inset-bottom, 0px)) - env(safe-area-inset-top, 0px);
    min-height: calc(100vh - env(safe-area-inset-bottom, 0px) - env(safe-area-inset-top, 0px));
    width: 100%;
    margin: 0;
    padding: 0;
    position: relative;
    overflow: hidden;
}
```

**Comment by Pietfro** [comment]
For anyone that is still struggling with the viewport sizing on iOS, here is the best working solution, at least in my case:
```
html,
body {
    height: 100%;
    width: 100%;
    max-height: calc(100vh - env(safe-area-inset-bottom, 0px) - env(safe-area-inset-top, 0px));
    margin: 0;
    padding: 0;
    position: relative;
    overflow: hidden;
}
```

**Comment by raphaelarias** [comment]
I fixed this problem by adding a splash screen.

**Comment by terreng** [comment]
For anyone reading over all this, wading through different answers: reapplying #45 is the real solution here.

Add `[wkWebView.scrollView setContentInsetAdjustmentBehavior:UIScrollViewContentInsetAdjustmentNever];` before `wkWebView.UIDelegate = self.uiDelegate;` in `CDVWebViewEngine.m`
