### ISSUE TITLE
Getting Duplicate Symbol Error

### ISSUE THREAD

**Issue by prof-jagpreet** [apache/cordova-plugin-wkwebview-engine#111]
I installed the plugin on my ionic 4 but when i try to build ios i got following errors:

Please helP

❌  duplicate symbol _OBJC_IVAR_$_CDVWKWebViewEngine._engineWebView in
> CDVWKWebViewEngine-07751f6d526f52a1b46a4e7e94d910b7d6602b988850a64ca207ba0ff58e01cc.o
> CDVWKWebViewEngine-07751f6d526f52a1b46a4e7e94d910b7944c6edd8caffceca19e29d2ab11634d.o

❌  duplicate symbol _OBJC_IVAR_$_CDVWKWeakScriptMessageHandler._scriptMessageHandler in
> CDVWKWebViewEngine-07751f6d526f52a1b46a4e7e94d910b7d6602b988850a64ca207ba0ff58e01cc.o
> CDVWKWebViewEngine-07751f6d526f52a1b46a4e7e94d910b7944c6edd8caffceca19e29d2ab11634d.o

❌  duplicate symbol _OBJC_IVAR_$_CDVWKWebViewEngine._weakScriptMessageHandler in
> CDVWKWebViewEngine-07751f6d526f52a1b46a4e7e94d910b7d6602b988850a64ca207ba0ff58e01cc.o
> CDVWKWebViewEngine-07751f6d526f52a1b46a4e7e94d910b7944c6edd8caffceca19e29d2ab11634d.o

❌  duplicate symbol _OBJC_CLASS_$_CDVWKWeakScriptMessageHandler in
> CDVWKWebViewEngine-07751f6d526f52a1b46a4e7e94d910b7d6602b988850a64ca207ba0ff58e01cc.o
> CDVWKWebViewEngine-07751f6d526f52a1b46a4e7e94d910b7944c6edd8caffceca19e29d2ab11634d.o

❌  duplicate symbol _OBJC_METACLASS_$_CDVWKWeakScriptMessageHandler in
> CDVWKWebViewEngine-07751f6d526f52a1b46a4e7e94d910b7d6602b988850a64ca207ba0ff58e01cc.o
> CDVWKWebViewEngine-07751f6d526f52a1b46a4e7e94d910b7944c6edd8caffceca19e29d2ab11634d.o

❌  duplicate symbol _OBJC_CLASS_$_CDVWKWebViewEngine in
> CDVWKWebViewEngine-07751f6d526f52a1b46a4e7e94d910b7d6602b988850a64ca207ba0ff58e01cc.o
> CDVWKWebViewEngine-07751f6d526f52a1b46a4e7e94d910b7d6602b988850a64ca207ba0ff58e01cc.o

❌  duplicate symbol _OBJC_METACLASS_$_CDVWKWebViewEngine in
> CDVWKWebViewEngine-07751f6d526f52a1b46a4e7e94d910b7d6602b988850a64ca207ba0ff58e01cc.o
> CDVWKWebViewEngine-07751f6d526f52a1b46a4e7e94d910b7944c6edd8caffceca19e29d2ab11634d.o

❌  duplicate symbol _OBJC_CLASS_$_CDVWKWebViewUIDelegate in
> CDVWKWebViewUIDelegate-07751f6d526f52a1b46a4e7e94d910b72bbdb68849c7d95efb2ad1d736bf81ed.o
> CDVWKWebViewUIDelegate-07751f6d526f52a1b46a4e7e94d910b7cc254382ae625c2ac87481a8eadc30a9.o

❌  duplicate symbol _OBJC_METACLASS_$_CDVWKWebViewUIDelegate in
> CDVWKWebViewUIDelegate-07751f6d526f52a1b46a4e7e94d910b72bbdb68849c7d95efb2ad1d736bf81ed.o
> CDVWKWebViewUIDelegate-07751f6d526f52a1b46a4e7e94d910b7cc254382ae625c2ac87481a8eadc30a9.o

❌  duplicate symbol _OBJC_IVAR_$_CDVWKWebViewUIDelegate._title in
> CDVWKWebViewUIDelegate-07751f6d526f52a1b46a4e7e94d910b72bbdb68849c7d95efb2ad1d736bf81ed.o
> CDVWKWebViewUIDelegate-07751f6d526f52a1b46a4e7e94d910b7cc254382ae625c2ac87481a8eadc30a9.o

❌  duplicate symbol _OBJC_METACLASS_$_CDVWKProcessPoolFactory in
> CDVWKProcessPoolFactory-07751f6d526f52a1b46a4e7e94d910b725bb3f9e3183e9148a0fb89c1412e903.o
> CDVWKProcessPoolFactory-07751f6d526f52a1b46a4e7e94d910b7db0f0d90d4b9a9a62b2f859d1dadf899.o

❌  duplicate symbol _OBJC_IVAR_$_CDVWKProcessPoolFactory._sharedPool in
> CDVWKProcessPoolFactory-07751f6d526f52a1b46a4e7e94d910b7db0f0d90d4b9a9a62b2f859d1dadf899.o
> CDVWKProcessPoolFactory-07751f6d526f52a1b46a4e7e94d910b725bb3f9e3183e9148a0fb89c1412e903.o

❌  ld: 14 duplicate symbols for architecture arm64

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason 😉 
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by prof-jagpreet** [comment]
I thought simple will be the best.. just installed ionic 4 create a build.

Build succeed.

Installed this plugin and i get above errors. 

I thought this simple explanation will be good rather than giving huge information

**Comment by timbru31** [comment]
Blind guess since you mention Ionic: I bet you already have the cordova-plugin-ionic-webview installed that's basically a fork of this plugin. Use either one.

**Comment by prof-jagpreet** [comment]
Thanks for the Hint. But i just installed Ionic 4. 
But i never installed cordova-plugin-ionic-webview plugin myself. I think it comes already built in.

Will give it a try.
Thanks

**Comment by spinninghamster** [comment]
I had this happen to me by accident today. Exact same error. I had Ionic WKWebview installed **and** the Apache WKWebView. Removed one of them and everything was fine. You may need to completely delete the platform folder however.

**Comment by jcesarmobile** [comment]
`cordova-plugin-ionic-webview` started as a fork of this plugin, so the class are named the same way. That plugin is installed by default on Ionic apps, so you need to uninstall it to install this one.
