### ISSUE TITLE
Input field not losing focus iOS 12.x

### ISSUE THREAD

**Issue by globules-io** [apache/cordova-plugin-wkwebview-engine#112]
# Bug Report

## Problem
1- Touch input type text
2- Keyboard shows
3- Touch outside the field
4- Field not losing focus, keyboard not hiding

### Environment, Platform, Device
Verified with iOS 12.4/13.0

### Version information
Cordova 9.0
Cordova iOS 5.0.1
WkWebView 1.2.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by spinninghamster** [comment]
I tried in the simulator and it works with iOS 12.4. Is this happening in the simulator or actual device?

**Comment by globules-io** [comment]
Actual device. More info: the under div covering the entire page has a touch event (non trapped). So it feels like the keyboard listener doesn't receive the touch event, which I thought was not possible as the webview would receive the touch before the dom...

**Comment by globules-io** [comment]
![ezgif com-optimize](https://user-images.githubusercontent.com/13317159/65893996-f81ff200-e376-11e9-933e-1cb7a34b1e7a.gif)

So once the keyboard is up, I try touching out on the background (you can't see that) then I touch twice the ? icon to show a popup and the keyboard is still here.

**Comment by globules-io** [comment]
Here I recorded a video. Here's what happens:
1- Touch on input, keyboard shows up
2- Touch on background (you can't see that) and the keyboard is still up
3- Touch on (?) help bubble to show a popup, keyboard still here.

![ezgif com-optimize (1)](https://user-images.githubusercontent.com/13317159/65894439-c9564b80-e377-11e9-89cf-a1d1b8314714.gif)

**Comment by globules-io** [comment]
More info: this view is sitting outside the field of view when created (like -screen_width offset), then slides in later on (like a carousel).
If I create a "normal" view (not outside of screen) it works normally.

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
