### ISSUE TITLE
scroll does not work in on some pages

### ISSUE THREAD

**Issue by 99electronic** [apache/cordova-plugin-wkwebview-engine#117]
On certain pages when they load (long lists for instance) I can't scroll down it is like frozen. This happens only when wkwebview plugin is used. If I click on one of the items on the list which pushes another page the page loads and when I go back scroll is working. This happens on multiple pages and always just the ones I get into from navigator, if I go deeper to next page and then back, it works and scrolls fine. Also if I open page which is not first from the navigator menu, even if it is long and needs scroll it works OK.
I tried to create long page without ajax loading, and it is same, if it is first level from navigator scroll does not work. 
Any suggestion would be appreciated.

**Comment by breautek** [comment]
You should not delete the bug template and instead fill it out properly as it gives us necessary information about your environment to help you.

Based on your description however, it sounds more of an html/css problem. Are you able to make a sample reproduction app that demonstrates your issue? In this case, I think that would be help greatly.

https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by 99electronic** [comment]
I agree, it is some html/css issue but I can't find it it is very frustrating by now. When I create simple plain app with nothing in it it does scroll. Also my app works fine in uiwebview but when wkwebview is used, the list of items is not scrollable no matter what I do. I just hope someone here had this issue before and could know why. The app is very complicated and I tried to debug, no results... I got to the point where I can kind of scroll but it is  pulling back and I can see just part of the list hidden under the bottom of the page but goes back once I let go finger scrolling.

**Comment by 99electronic** [comment]
I figured this one out. The div element which contains the list needs to have css: display: block;
    height: 100%;
    overflow: auto;
    -webkit-overflow-scrolling: touch;
    -ms-overflow-style: none;
    -ms-scroll-snap-type: mandatory;

which fix the issue. I do not have to use this css when uiwebview is used.

**Comment by danchaseCTS** [comment]
So you eliminated the scrolling issue, by eliminating the need to scroll? You simply made the div scroll instead. This can't be the fix.

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
