### ISSUE TITLE
wkwebview + ios 13.2 not working

### ISSUE THREAD

**Issue by globules-io** [apache/cordova-plugin-wkwebview-engine#121]
# Bug Report

### What does actually happen?
App crashes at splashscreen, log is flooded with
[Process] kill() returned unexpected error 1

## Information
https://bugs.webkit.org/show_bug.cgi?id=202173
https://stackoverflow.com/questions/58321114/why-i-get-the-console-warning-process-kill-returned-unexpected-error-1-when 
https://stackoverflow.com/questions/58732413/ionic-ios-13-2-bug-app-crash-kill-returned-unexpected-error
https://forums.developer.apple.com/thread/123782

Posting here in case there is a possible fix on this end of things since all apps are affected. I understand this is an Apple bug BUT : 
**The thing that I have noticed is that if you inspect via Safari and reload the document, the app works.** But unless I inspect and reload, it does not most of the time and is stuck at the splash screen. Sometimes it works, it's very random.
So again, since the app works when I reload, is it possible to add a fix that starts the webview document later or something?

### Environment, Platform, Device
cordova-ios@5.0.1
cordova@9.0.1
ios@13.2, 13.3 beta 1, 2
xcode 11.2
macos 10.15.2b

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by globules-io** [comment]
Was related to splashscreen

**Comment by mkurzweil** [comment]
I'm facing currently the same issue. Did you find a workaround how the splashscreen can still be used?

**Comment by globules-io** [comment]
@mkurzweil In our case, a resource wasn't loaded properly which induced a crash right before splashscreen.hide() and then the splashscreen would not hide. The error flood is just an Apple "feature".

**Comment by ish3lan** [comment]
I am facing the same issue, and wondering what will happen if submit the app to appstore? will it be rejected? when people downloads it will they be able to run it many times? or they will face the same issue?

**Comment by ralphcorleone** [comment]
Same question @ish3lan

**Comment by kokitang** [comment]
Any fix?
