### ISSUE TITLE
Still getting "UIWebView" warning when compiling to iOS through Phonegap Builder

### ISSUE THREAD

**Issue by jtibbles** [apache/cordova-plugin-wkwebview-engine#125]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Support Question

### Environment, Platform, Device

I'm making an app for Android an iOS using Phonegap Builder as the compiler. It compiles fine but when I submit the .ipa file for testing on iOS I receive the following warning:

"ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs"

This is the same warning I was receiving prior to using this plugin, so it doesn't seem to be affecting the outcome.

Looking at the list of accepted plugins I an see cordova-plugin-wkwebview-engine (spec 1.2.1) is being recognised. I also added the following to my config.xml file:

```
<plugin name="cordova-plugin-wkwebview-engine" />
<feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
</feature>
<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
<preference name="AllowBackForwardNavigationGestures" value="false" />
<preference name="Allow3DTouchLinkPreview" value="false" />
```

I know this is just a warning for now, so the app is still working but it doesn't seem to have converted to WKWebView.

### Version information

Phonegap CLI-9-0-0
Phonegap Builder version 2
cordova-plugin-wkwebview-engine 1.2.1
Standard HTML, javascript
Other plugins used:

cordova-plugin-device" spec="1.1.7"
cordova-plugin-app-version" spec="0.1.9"
cordova-plugin-wkwebview-engine"
cordova-plugin-device-motion" spec="1.2.5"
cordova-plugin-device-orientation" spec="1.0.7"
cordova-plugin-dialogs" spec="1.2.1"
cordova-plugin-geolocation" spec="2.1.0" 
cordova-plugin-globalization" spec="1.0.9"
cordova-plugin-inappbrowser" spec="1.3.0"
cordova-plugin-network-information" spec="1.2.1" 
cordova-plugin-splashscreen" spec="3.2.2" 
cordova-plugin-statusbar" spec="2.1.3"
cordova-plugin-whitelist" spec="1.2.2"
cordova-plugin-vibration"  spec="3.1.1"
cordova-plugin-contacts" spec="3.0.1"
cordova-plugin-android-permissions

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
You should upgrade to the latest `cordova-ios@5.1.1` release and use the `WKWebViewOnly` preference. I don't think there is official documentation (yet) but more details about the preference can be found on the PR https://github.com/apache/cordova-ios/pull/715

https://cordova.apache.org/announcements/2019/12/02/cordova-ios-release-5.1.1.html

The warning occurs even with the wkwebview plugin because the core framework still references `UIWebview`, but version 5.1.1 with the `WkWebViewOnly` preference hides references via a compiler flag.

**Comment by jtibbles** [comment]
Thanks for the quick response. 
I'm using Phonegap Build so I don't compile locally, I can only specify "phonegap-version cli-9.0.0" which supports Android Phonegap version 8.0.0 and iOS phonegap version 5.0.1  There is no higher cli at the moment. But as 5.1.1 has only come out today and the webview is a big sticking point I suspect Phonegap will update their cli shortly.

**Comment by breautek** [comment]
The best course of action is to raise the issue with the phonegap team at https://github.com/phonegap/phonegap-cli
