### ISSUE TITLE
Can I judge whether page switching is due to 'swipe navigation'?

### ISSUE THREAD

**Issue by eliot-ye** [apache/cordova-plugin-wkwebview-engine#126]
# Feature Request

## Motivation Behind Feature

When I see this plugin and see the 'enabling navigation gears ("swipe navigation") function, I am very excited, which is very cool.

But this is a Cordova plugin, corresponding to webapp. Generally speaking, the HTML page switching in our Cordova app will start the page switching animation, which conflicts with the 'swipe navigation' animation.

Can I have a callback triggered after the completion of 'swipe navigation' to judge whether to start page switching animation?

## Feature Description

```js
document.addEventListener("beforeBackForwardNavigationGestures", function(){
  // Trigger back forward navigation gears, do some thing
})
```

**Comment by jcesarmobile** [comment]
no, it's not possible
