### ISSUE TITLE
iOS 13 DisallowOverscroll not working

### ISSUE THREAD

**Issue by oveshparasara** [apache/cordova-plugin-wkwebview-engine#128]
i have added config.xml <preference name="DisallowOverscroll" value="true" />
also added forceOverscroll=false  but not working ios 13

**Comment by padinko** [comment]
this happen only when
```xml
    <platform name="ios">
        <preference name="deployment-target" value="13.0"/>
    </platform>
```

is set

**Comment by Noteofman** [comment]
Any movement here?

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
