### ISSUE TITLE
CodePush plugin not working when used with this plugin.

### ISSUE THREAD

**Issue by Anuj-logiciel** [apache/cordova-plugin-wkwebview-engine#130]
# Bug Report
CodePush plugin when used with this plugin.

## Problem

Wkwebviewengine is not supporting Hotfix updated by using codepush plugin.

### What is expected to happen?

When I used codepush plugin with UIWebview, all things were working fine and I was easily able to update my app using cordova-plugin-code-push. After adding wkwebview(this plugin). It stopped updating via codepush.  It should work as works in uiwebview.

### Earlier Reported -
Earlier Reported on cordova codepush plugin. Here's [Issue Reference](https://github.com/microsoft/cordova-plugin-code-push/issues/603)

**Comment by dandouglas** [comment]
This is an issue the code push plugin and not the wkwebview plugin.

However v1.11.16  of the Code Push plugin works **but** it (and all the latest versions) has references to UIWevView and Apple will reject you app.  Microsoft are not going to update it either so I'd look for an alternative.

**Comment by tudordumitriu** [comment]
@dandouglas if this is true then this is quite a problem for lots or teams
Considering the fact that Apple will start rejecting and considering that MS invested quite a lot in this platform I would say that the should be updating it sometime soon, but You said "Microsoft are not going to update it", is that an official position from MS?

**Comment by dandouglas** [comment]
@tudordumitriu I’m not sure if it’s their official stance but you can check out the comment in an open issue here https://github.com/microsoft/cordova-plugin-code-push/issues/594#issuecomment-588013184

**Comment by tudordumitriu** [comment]
Thanks, so this doesn't seem to an alternative to the old cordova hot code push plugin (at least yet),
Even if they will get it working with WKWevView you're still getting rejected by Apple because of the UIWebView references, so the MS team would nee to fix both issues.

**Comment by dandouglas** [comment]
Exactly, and from looking at the comments on the open issue it doesn't look like they intend to update it any time soon.  We rely heavily on codepush as we have almost a hundred live apps essentially built from one code base (we offer a self build template solution) so it means every small update at the moment requires nearly a hundred store submissions.

There are offer options such as Ionic which offer a similar service that may be worth looking at.  But for now I just had to remove the plugin as all new submissions from the 1st April will be blocked if they contain UiWebView references.

**Comment by jcesarmobile** [comment]
As it has been mentioned, this is something the code push plugin should fix
