### ISSUE TITLE
April 2020. UIWebview will be rejected by Apple

### ISSUE THREAD

**Issue by GimpMaster** [apache/cordova-plugin-wkwebview-engine#131]
Not sure if this has been reported but I got this message from Apple on latest push.

"Apple will stop accepting submissions of apps that use UIWebView APIs starting from April 2020."

Is cordova going to finally switch over to wkwebkit by default? 
Also is this plugin still needed: "cordova-plugin-wkwebview-file-xhr"

I couldn't tell by this message in the README.md

"In iOS 9, Apple has fixed the issue present through iOS 8 where you cannot load locale files using file://, and must resort to using a local webserver. "

**Comment by breautek** [comment]
As of `cordova-ios@5.1.1`, there is a preference `<preference name="WKWebViewOnly" value="true" />` which hides all the `UIWebView` references behind a compiler flag. With this flag, it is expected that you have a wkwebview plugin installed (the two common ones are either apache's wkwebview engine, or ionic's)

If you use the inappbrowser plugin, then you should also use the latest version of that plugin, which will respect the `WKWebViewOnly` flag.

Do note that other plugins may also reference these deprecated APIs, and they may need to be updated as well. Common offenders are social media plugins like facebook, google, etc.

> Is cordova going to finally switch over to wkwebkit by default?

Next major releases will have wkwebview built-in.

> Also is this plugin still needed: "cordova-plugin-wkwebview-file-xhr"

I'm not sure as in my apps I am still using the local webserver plugin (which isn't exactly ideal either), but I would invite you to our [slack](http://slack.cordova.io/) for questions like this.

**Comment by GimpMaster** [comment]
Thanks @breautek . I knew about those preferences, I actually use them in a different app, this was just a quick push on a test app. 

Its just I had not seen anyone post that April 2020 is the day that apple stops accepting them.

Thanks

**Comment by GimpMaster** [comment]
Here is the official site I just found.

https://developer.apple.com/news/?id=12232019b

**Comment by breautek** [comment]
The deadlines were April 2020 for new apps, and December 2020 for existing apps I believe.
