### ISSUE TITLE
cookies / cache is not saved using iframe and wkwebview plugin

### ISSUE THREAD

**Issue by matrixreal** [apache/cordova-plugin-wkwebview-engine#132]
hello guys,
cordova ios 5.1.1 without wkwebview plugins work fine
but with this plugin, cookies or cache is not saved thru iframe after app restart
any solution?
thanks

**Comment by samulla** [comment]
Did you get any solution to this? I am sailing in the same boat :(

**Comment by matrixreal** [comment]
no

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
