### ISSUE TITLE
Enhance installation by inlining the configuration variables

### ISSUE THREAD

**Issue by timbru31** [apache/cordova-plugin-wkwebview-engine#133]
Inspired by [Niklas recent blog post](https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html), I'd like to discuss if we should inline the configuration variables to the plugin.xml:

```xml

    <feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>

    <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
```

Ionic's fork does this, too: https://github.com/ionic-team/cordova-plugin-ionic-webview/blob/master/plugin.xml#L68-L71

IMO providing a plugin that is just "ready to use" after installing would enhance the user experience and decrease the amount of support issues/questions.

Any thoughts, e.g., @erisu @NiklasMerz

**Comment by NiklasMerz** [comment]
I thought about that too while writing the post. I definitely support it.

But we need to revise the docs anyway once the next cordova-ios major version is released.

**Comment by timbru31** [comment]
General docs improvement is one of our bigger todos, that's true. Should we further discuss this on the mailing list? Not all members are subscribed to the GitHub issues noise. :D

**Comment by NiklasMerz** [comment]
For this change I would just do a PR and merge it. Once cordova-ios is released or about to release we need to check this plugins docs anyway.

**Comment by erisu** [comment]
It is already there.

The reason I had it included in the steps is because some users it does not set. I think it was related to the config munging issue which I reverted a PR change that caused it. Next major contains the revert..

https://github.com/apache/cordova-plugin-wkwebview-engine/blob/master/plugin.xml#L47-L52

**Comment by timbru31** [comment]
Oh neat! Somehow I've overlooked these lines of code.
