### ISSUE TITLE
Ionic 3 (iOS) - Custom ion-icon CORS issue

### ISSUE THREAD

**Issue by molinet88** [apache/cordova-plugin-wkwebview-engine#134]
# Bug Report
## Problem
Custom svg ionic icons are not displayed on iOS because of a CORS issue.

### What is expected to happen?
WKWebview should allow custom icons to be displayed as they are local resources.

### What does actually happen?
On iOS, when trying to load a custom icon, CORS error is thrown:
```
Failed to load resource: Origin null is not allowed by Access-Control-Allow-Origin.
file:///private/var/containers/Bundle/Application/.../www/assets/imgs/arrow-down.svg
```

### Command or Code
Creating custom icon:
```
ion-icon {
  &[class*="custom-"] {
    mask-size: contain;
    mask-position: 50% 50%;
    mask-repeat: no-repeat;
    background: currentColor;
    width: 1em;
    height: 1em;
  }
  &[class*="custom-arrow-down"] {
    mask-image: url(../assets/imgs/arrow-down.svg);
  }
}
```

Using custom icon:
`<ion-icon name="custom-arrow-down" color="primary"></ion-icon>`

### Environment, Platform, Device
iPhone 7 Plus

### Version information

Ionic
```
Ionic Framework: ionic-angular 3.9.5
ionic (Ionic CLI): 3.20.1
@ionic/cli-utils: 1.19.3
@ionic/app-scripts: 3.2.3
```
Cordova
```
cordova (Cordova CLI): 9.0.0 (cordova-lib@9.0.1)
Cordova Platforms: ios 5.1.1
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

Related:
https://forum.ionicframework.com/t/ionic-3-custom-svg-icon-cors-issue/156796
https://stackoverflow.com/questions/54667997/ionic-3-custom-svg-icon-cors-issue

**Comment by jcesarmobile** [comment]
WKWebView has problem accessing local files when loaded from file:// protocol, see https://issues.apache.org/jira/browse/CB-10143

Since you are using ionic, you can use `cordova-plugin-ionic-webview`
