### ISSUE TITLE
iOS 13.4 Inline Video

### ISSUE THREAD

**Issue by bcolflesh** [apache/cordova-plugin-wkwebview-engine#135]
# Bug Report

## Problem
Prior to 13.4, setting `<preference name="AllowsInlineMediaPlayback" value="true" />` and webkit-playsinline and playsinline on the <video> src allowed videos to play inline.

### What is expected to happen?
Video playing inline without the native player opening.

### What does actually happen?
The native player open over top.

### Environment, Platform, Device

iOS 13.4

### Version information
9.0.0 (cordova-lib@9.0.1)

Requirements check results for ios:
Apple macOS: installed darwin
Xcode: installed 11.4
ios-deploy: installed 1.10.0
CocoaPods: installed 1.9.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by donemuhendislik** [comment]
> # Bug Report
> ## Problem
> Prior to 13.4, setting `<preference name="AllowsInlineMediaPlayback" value="true" />` and webkit-playsinline and playsinline on the src allowed videos to play inline.
> 
> ### What is expected to happen?
> Video playing inline without the native player opening.
> 
> ### What does actually happen?
> The native player open over top.
> 
> ### Environment, Platform, Device
> iOS 13.4
> 
> ### Version information
> 9.0.0 (cordova-lib@9.0.1)
> 
> Requirements check results for ios:
> Apple macOS: installed darwin
> Xcode: installed 11.4
> ios-deploy: installed 1.10.0
> CocoaPods: installed 1.9.0
> 
> ## Checklist
> * [x]  I searched for existing GitHub issues
> * [x]  I updated all Cordova tooling to most recent version
> * [x]  I included all the necessary information above

I need help for the same problem. I ve been working on it for 3 days. I read some old information about this for may help me... <preference name="AllowInlineMediaPlayback" value="true" /> not working and adding webkit-playsinline & playsinline attribute into the video tag... By the way, I have same configuration...

**Comment by bcolflesh** [comment]
Sorry for the delayed response - this was for a Brightcove embed via an iframe (their preferred embed method). It no longer works on iOS, I think they FUBAR'd iframe permissions or never correctly added them from UIWebView, so I switched to embedding via a JavaScript function with a callback that loads/plays the content once it's ready.

Unfortunately lots of functionality is missing or broken in WKWebView, I assume they are purposely sabotaging it to drive away web apps and force people to use the Apple Dev environment.

**Comment by donemuhendislik** [comment]
> Sorry for the delayed response - this was for a Brightcove embed via an iframe (their preferred embed method). It no longer works on iOS, I think they FUBAR'd iframe permissions or never correctly added them from UIWebView, so I switched to embedding via a JavaScript function with a callback that loads/plays the content once it's ready.
> 
> Unfortunately lots of functionality is missing or broken in WKWebView, I assume they are purposely sabotaging it to drive away web apps and force people to use the Apple Dev environment.

Thanks a lot for your response 👏🏻 After i read your comment, i looked for all solutions, and you re right... I cancelled writing code for that module. I used normal photo slide show instead of this. I hope, phonegap can find a solution about this. We cannot be forced to use original Apple sources ! Hybrid is always best... Thanks again for your best answer... Stay in health 🙏🏻

**Comment by Mizan-Rifat** [comment]
I've the same problem.. is there any solution out there??

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
