### ISSUE TITLE
iOS 13 Sandbox Issue - WebPageProxy::Ignoring request to load this main resource because it is outside the sandbox

### ISSUE THREAD

**Issue by gasci** [apache/cordova-plugin-wkwebview-engine#140]
# Bug Report
Received an unexpected URL from the web process: 'file:///Users/gokasci/Library/Developer/CoreSimulator/Devices/2EFBFE26-6A43-4F8C-A502-2AAE7CA5B67A/data/Containers/Bundle/Application/7ED4101B-FDCD-40E0-AD59-A24B37829E40/Curiosmo.app/www/pages/templates/homepage.html'
WebPageProxy::Ignoring request to load this main resource because it is outside the sandbox

## Problem
I receive a sandbox error when I try to direct the user to a local .html file in my app:
'file:///Users/gokasci/Library/Developer/CoreSimulator/Devices/2EFBFE26-6A43-4F8C-A502-2AAE7CA5B67A/data/Containers/Bundle/Application/7ED4101B-FDCD-40E0-AD59-A24B37829E40/Curiosmo.app/www/pages/templates/homepage.html' on iOS 13. (It works fine below iOS 13.)

### What is expected to happen?
After user login on 'index.html' (the user can receive a token from the server), the user should be directed to 'homepage.html'

### What does actually happen?
After the user login on 'index.html', the user is stuck on 'index.html' and the device gives the error above.

## Information
https://stackoverflow.com/questions/49638653/load-local-web-files-resources-in-wkwebview
https://stackoverflow.com/questions/40123321/wkwebview-run-local-html-in-document-received-an-unexpected-url-from-the-web-p
https://forums.developer.apple.com/thread/95473

### Command or Code
cordova platform add ios
cordova plugin add cordova-plugin-wkwebview-engine

### Environment, Platform, Device
iOS 13.2.2, cordova-ios 5.1.1, iPhone 6S

### Version information
cordova-cli 9.0.0

android 8.1.0
browser 6.0.0
ios 5.1.1
osx 5.0.0

cordova-pdf-generator 2.0.8 "PDFGenerator"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-apprate 1.5.0 "AppRate"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-calendar 5.1.5 "Calendar"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-customurlscheme 4.4.0 "Custom URL scheme"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-firebase-analytics 4.1.2 "FirebaseAnalyticsPlugin"
cordova-plugin-firebase-messaging 4.1.1 "FirebaseMessagingPlugin"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-ios-camera-permissions 1.2.0 "iOS Permissions"
cordova-plugin-media-capture 3.0.2 "Capture"
cordova-plugin-native-settings 1.0.0 "NativeSettings"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-navigationbar-color 0.0.8 "NavigationBar"
cordova-plugin-purchase 9.0.0 "Purchase"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine"
cordova-plugin-wkwebview-file-xhr 2.1.4 "Cordova WKWebView File XHR Plugin"
cordova-plugin-x-socialsharing 5.4.7 "SocialSharing"
cordova-support-android-plugin 1.0.1 "cordova-support-android-plugin"
cordova-support-google-services 1.4.0 "cordova-support-google-services"
cordova.plugins.diagnostic 5.0.1 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to a most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
how do you redirect to homepage.html?
can you provide a sample app?

**Comment by breautek** [comment]
> Ignoring request to load this main resource because it is outside the sandbox

This sounds like you're trying to access a resource that is "outside" of your app.

> (It works fine below iOS 13.)

This suggests to me you're trying to use the exact same URL (maybe hard-coded) on different simulators.

Make sure you're using relative paths, not absolute paths. You cannot after all determine the UUID portion of the url on iOS.

**Comment by gasci** [comment]
While testing in a blank app, we realized that putting index.html in a folder and redirecting it to another .html in another folder outside the index.html's folder causes the problem:

-folder1
--index.html
-folder2
--redirected.html

**Comment by yumi19880806** [comment]
try to use
NSString *path = [[NSBundle mainBundle] pathForResource:@"index" ofType:@"html"];
NSString *htmlContent = [NSString stringWithContentsOfFile:path encoding:NSUTF8StringEncoding error:nil];
[self.webView loadHTMLString:htmlContent baseURL:fileURL];
i resolve it on ios14 beta

**Comment by SapiensEduvision** [comment]
I'm having the same problem, running on iOS 13 currently and using Xcode 11.7 beta, I'm new to iOS so I don't have an idea of how to solve it. Just built my existing cordova project, using cordova ios 6.1, I tried downgrade to 5.1 but the error still appearing

**Comment by araafat3** [comment]
Hi @yumi19880806 
where you put this code to solve it?

**Comment by Booyoun-Kim** [comment]
I used @gasci 's solution and it worked!

This is my folder structure.

```
-en
--index.html
-ko
--index.html
```

It failed to move en/index.html to ko/index.html. I created a simple html page in www folder. 

```
<html>
<head>
<meta charset='utf-8'>
<meta http-equiv="refresh" content="0; url=./en/index.html" />
<title>Main Page</title>
</head>
<body>
</body>
</html>
```

```
index.html
-en
--index.html
-ko
--index.html
```

Then I changed a config.xml. <content src="en/index.html" /> to <content src="index.html" />

```
<platform name="ios">
        <content src="index.html" />
</platform>
```

The error, "WebPageProxy::Ignoring request to load this main resource because it is outside the sandbox" is gone. Worked fine.
