### ISSUE TITLE
Property 'userAgent' not found on object of type 'CDVViewController *'

### ISSUE THREAD

**Issue by sanfordhuang** [apache/cordova-plugin-wkwebview-engine#142]
# Bug Report

## Problem
failure to build after add simple project for ios platform and show erros:
1. Property 'userAgent' not found on object of type 'CDVViewController*' in CDVWKWebviewEngine.m
2. Use of undeclared identifier 'CDVUserAgentUtil' in CDVWKWebViewEngine.m
3. Use of undeclared identifier 'CDVUserAgentUtil' in CDVWKWebViewEngine.m

### What is expected to happen?
run successfully
### What does actually happen?
failure to run and show the errors:
1. Property 'userAgent' not found on object of type 'CDVViewController*' in CDVWKWebviewEngine.m
2. Use of undeclared identifier 'CDVUserAgentUtil' in CDVWKWebViewEngine.m
3. Use of undeclared identifier 'CDVUserAgentUtil' in CDVWKWebViewEngine.m

### Command or Code

```
cordova create wkwvtest my.project.id wkwvtest
cd wkwvtest
cordova platform add https://github.com/apache/cordova-ios.git#master
cordova plugin add https://github.com/apache/cordova-plugin-wkwebview-engine.git#master
```

### Info
config.xml:
```
        <preference name="WKWebViewOnly" value="true" />
        <feature name="CDVWKWebViewEngine">
            <param name="ios-package" value="CDVWKWebViewEngine" />
        </feature>
        <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
```

### Version information
Cordova: 8.1.2
Xcode: 11.4

## Checklist
- [x ] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by CodeWithOz** [comment]
@sanfordhuang did you ever find a fix for this? Getting it now but with the [ionic-webview](https://github.com/ionic-team/cordova-plugin-ionic-webview/) plugin.

**Comment by gartner90** [comment]
I have this error too.

**Comment by sanfordhuang** [comment]
> @sanfordhuang did you ever find a fix for this? Getting it now but with the [ionic-webview](https://github.com/ionic-team/cordova-plugin-ionic-webview/) plugin.

I didn't use this plugin eventually with the new version cordova-ios. The WKWebView may built in  on new branch cordova-ios.

My finally command used:
```
cordova create wkwvtest my.project.id wkwvtest
cd wkwvtest
cordova platform add https://github.com/apache/cordova-ios.git#master
```

**Comment by vitto32** [comment]
I suppose this is related to:
https://github.com/apache/cordova-ios/commit/20248c196d35c9b8390dbbd2953f9bc1191b6c6d

**Comment by zhangv** [comment]
I was able to build successfully by removing the "cordova-plugin-wkwebview-engine"

`cordova plugin rm cordova-plugin-wkwebview-engine`

**Comment by vedatozkanTr** [comment]
when I by removing the "cordova-plugin-wkwebview-engine" then build successfully but IOS App rejected 
**Guideline 2.1 - Performance - App Completeness
We discovered one or more bugs in your app when reviewed on iPad and iPhone running iOS 13.5.1 on Wi-Fi.

Specifically, the buttons in the app were unresponsive.**


I have been looking at the forums for a long time but there is no solution. Cordova crash !!!!!!!
I think it's time to cross over to Xamarin. Nobody is interested.

**Comment by PawelGIX** [comment]
Why closed? is this already solved? I'm getting this error on latest version.

**Comment by breautek** [comment]
> Why closed? is this already solved? I'm getting this error on latest version.

The OP didn't mention what cordova-ios version they are using, but `wkwebview-engine` plugin only works on cordova-ios 5 or lower.

Cordova-ios@6 has wkwebview built in making this plugin obsolete.

**Comment by PawelGIX** [comment]
You're right, I found this information finally somewhere, thanks

**Comment by retoheusser** [comment]
Just for the record: I got this error after upgrading the Cordova CLI to version 10 (`npm i -g cordova`) and adding this plugin with Cordova 10 `cordova plugin add cordova-plugin-wkwebview-engine`. Cordova 10 suddenly added this plugin to the `devDependencies` in `package.json` compared to Cordova 9 where it was in `dependencies`. Going back to version 9 (`npm i -g cordova@9`) made the error go away.

**Comment by breautek** [comment]
> Cordova 10 suddenly added this plugin to the devDependencies in package.json

I believe this is intentional.

**Comment by rgfpy** [comment]
get the same error with cordova@10 and ios@6.1.0

**Comment by breautek** [comment]
> get the same error with cordova@10 and ios@6.1.0

This plugin is not compatibile with cordova-ios@6.x. 6.x has WKWebVIew implemented at its core, making this plugin obsolete, as mentioned [earlier](https://github.com/apache/cordova-plugin-wkwebview-engine/issues/142#issuecomment-660107853)
