### ISSUE TITLE
How to disable "screen scaling"?

### ISSUE THREAD

**Issue by AbdullaevTimur** [apache/cordova-plugin-wkwebview-engine#146]
When using the plugin and geastures, the screen zoom in or zoom out. It breaks UI. How can I disable this feature?

**Comment by JamalAPI** [comment]
May be you need to include **user-scalable=no** as shown below?
````
<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, maximum-scale=1, `user-scalable=no">
````

**Comment by pefann** [comment]
same problem there, even
`<meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height, target-densitydpi=device-dpi">` doesn't work

**Comment by PawelGIX** [comment]
Nothing seems to work. I can't disable scaling

**Comment by Mohammed-Rashed** [comment]
`<meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">`
work for me

**Comment by breautek** [comment]
Mohammed's answer is how you disable webview scrolling.

If you need more information about the viewport meta tag, the link below will probably help.

https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag
