### ISSUE TITLE
BackgroundColor preference doesn't work

### ISSUE THREAD

**Issue by devXpro** [apache/cordova-plugin-wkwebview-engine#149]
After switching to a new cordova-plugin-wkwebview-engine preference BackgroundColor stopped working. Now it always white. 
`<preference name="BackgroundColor" value="#222f73"/>`

To change the color, I need to edit the [source code of this plugin](https://stackoverflow.com/questions/44798901/how-to-change-cordova-wkwebview-engine-background-colour), but it is not very convenient.

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
