### ISSUE TITLE
Origin null is not allowed by Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by PawelGIX** [apache/cordova-plugin-wkwebview-engine#150]
# Bug Report

## Problem
No internet connection to server

### What is expected to happen?
Get propper Origin header?

### What does actually happen?
Origin header is null

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
