### ISSUE TITLE
CDVWKWebViewEngine userContentController didReceiveScriptMessage: does not get called 

### ISSUE THREAD

**Issue by aditisaini91** [apache/cordova-plugin-wkwebview-engine#151]
# Bug Report

## Problem
CDVWKWebViewEngine userContentController didReceiveScriptMessage: does not get called 
### What is expected to happen?

I am expecting that the method gets invoked and in turn executes the command from js

### What does actually happen?
Does not even gets invoked. And I also observed that "webView decidePolicyForNavigationAction: " keeps on calling with url "gap://ready". 

## Information

Cordova 5.1.1
 "cordova-plugin-wkwebview-engine": "1.2.1",

### Environment, Platform, Device

Using simulator iphone X 12.4

### Version information

Cordova 5.1.1
 "cordova-plugin-wkwebview-engine": "1.2.1",
xcode 11.3

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
