### ISSUE TITLE
I've added the plugin with its configuration but my app is rejected by app store

### ISSUE THREAD

**Issue by dedo2662888** [apache/cordova-plugin-wkwebview-engine#153]
# Bug Report

## Problem
it's still showing me "ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview). "
### What is expected to happen?
It should only use WKWebView instead of UIWebView 

### What does actually happen?
it still shows the same issue just like there is no WKWebView 

## Information

i don't have any extra plugins installed in my app only "whitelist" and "WKWebView-engine"

### Environment, Platform, Device

Cordova ios

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
See https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html

**Comment by dedo2662888** [comment]
i've done all the steps of it already but still shows me the same response

**Comment by breautek** [comment]
If you're using cordova-ios@5.1.1, have a wkwebview plugin such as this one, and is using the wkwebviewonly flag and you're still receiving the error then you must have a third-party plugin installed that is still referencing the `UIWebView`.

If you want further help, you'll going to need to supply the outputs of:

```
cordova -v
cordova platform ls
cordova plugin ls
```
