### ISSUE TITLE
WKWebView not work for me

### ISSUE THREAD

**Issue by Developer3010** [apache/cordova-plugin-wkwebview-engine#155]
# Bug Report

Apple continually rejects my application saying it does not use the WKWebView despite the plugin being installed and the options set within the config.xml file

## Problem

Using Apache Cordova, I installed this plugin, but it doesn't work, when I upload my app to the app store I receive an error email indicating that I am still using the UIWebView, when instead I should use the WKWebView.
I also put all the options in the config.xml file, just like the documentation says, but nothing to do, apple always refuses my application.
What am I doing wrong?

### What is expected to happen?

I expect the plugin to load the WKWebView instead of the now deprecated UIWebView

## Information

"cordova-ios": "^5.1.1",
"cordova-plugin-wkwebview-engine": "^1.2.1"

### Environment, Platform, Device

Using:

iPhone 6s -> 13.4
iPhone 11 -> 13.5

### Version information

"cordova-ios": "^5.1.1",
"cordova-plugin-wkwebview-engine": "^1.2.1"
xcode 11.4.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
Can you please share your `config.xml` so we can verify that the options are set correctly? Sometimes it also helps to completely remove and re-add the iOS platform.  
If the issue still persist, then another plugin still contains deprecated UIWebView code - you will need to open Xcode and search for the plugin and contact their author(s).

**Comment by Developer3010** [comment]
This is my config.xml

<?xml version='1.0' encoding='utf-8'?>
<widget id="com.test.res" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <feature name="LocalStorage">
        <param name="ios-package" value="CDVLocalStorage" />
    </feature>
    <feature name="Console">
        <param name="ios-package" value="CDVLogger" />
        <param name="onload" value="true" />
    </feature>
    <feature name="HandleOpenUrl">
        <param name="ios-package" value="CDVHandleOpenURL" />
        <param name="onload" value="true" />
    </feature>
    <feature name="IntentAndNavigationFilter">
        <param name="ios-package" value="CDVIntentAndNavigationFilter" />
        <param name="onload" value="true" />
    </feature>
    <feature name="GestureHandler">
        <param name="ios-package" value="CDVGestureHandler" />
        <param name="onload" value="true" />
    </feature>
    <name>RES</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <allow-intent href="itms:*" />
    <allow-intent href="itms-apps:*" />
    <preference name="AllowInlineMediaPlayback" value="false" />
    <preference name="BackupWebStorage" value="cloud" />
    <preference name="DisallowOverscroll" value="false" />
    <preference name="EnableViewportScale" value="false" />
    <preference name="KeyboardDisplayRequiresUserAction" value="true" />
    <preference name="MediaPlaybackRequiresUserAction" value="false" />
    <preference name="SuppressesIncrementalRendering" value="false" />
    <preference name="SuppressesLongPressGesture" value="false" />
    <preference name="Suppresses3DTouchGesture" value="false" />
    <preference name="GapBetweenPages" value="0" />
    <preference name="PageLength" value="0" />
    <preference name="PaginationBreakingMode" value="page" />
    <preference name="PaginationMode" value="unpaginated" />
    **<feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>
    <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />**
</widget>

I only installed that plug-in, I don't have any more and I've already tried to remove and reinstall the IOS platform but it doesn't work anyway ...

**Comment by Developer3010** [comment]
I only installed that plug-in, I don't have any more and I've already tried to remove and reinstall the IOS platform but it doesn't work anyway ...

Here my config.xml, I had to rename it in txt because github didn't make me load it in xml.
[config.txt](https://github.com/apache/cordova-plugin-wkwebview-engine/files/4695281/config.txt)

**Comment by breautek** [comment]
Looks like you're missing the [WKWebViewOnly](https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html) flag.

Understandably because this was only posted as in a blog and is currently not reflected in documentation. With `cordova-ios@6` (not released, but currently in the voting process, this flag won't be needed)

**Comment by timbru31** [comment]
Please make sure to follow all steps of https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html - your config does not include the `WKWebViewOnly` flag.

**Comment by Developer3010** [comment]
I made an attempt to include "WKWebViewOnly" but once again apple refused the app.
As you know, there are two config files, one generated automatically by cordova when creating a project and one generated by the installation of the IOS platform.
I entered the WKWebViewOnly flag and the rest of the options in both config, but it still doesn't work, what am I doing wrong yet?

Cordova config.xml

[config-cordova.txt](https://github.com/apache/cordova-plugin-wkwebview-engine/files/4695462/config-cordova.txt)

iOS-config.xml

[config-ios.txt](https://github.com/apache/cordova-plugin-wkwebview-engine/files/4695463/config-ios.txt)

**Comment by erisu** [comment]
Can you also provide your `package.json` file?

**Comment by Developer3010** [comment]
Of course, here is my package.json file
[package-json.txt](https://github.com/apache/cordova-plugin-wkwebview-engine/files/4695566/package-json.txt)

**Comment by erisu** [comment]
Can you try these steps... You might have already done this but just one more time to make sure:

* Delete `platforms` directory
* Delete `plugins` directory
* Delete `node_modules` directory
* Delete `package-lock.json` file. Again, the lock file.
* `npm install` to refetch the node_modules
* `cordova prepare` to recreate the `platforms` and `plugins` directory
* `cordova build ios --device --release` to rebuild your app.
* Then do an upload test...

**Comment by Developer3010** [comment]
Thanks a lot, now I managed to upload it.
As for AJAX calls instead, they can be done, but only with the CORS parameters, correct? Or can't they just do it?

**Comment by breautek** [comment]
> As for AJAX calls instead, they can be done, but only with the CORS parameters, correct? Or can't they just do it?

If you're making a request to a remote server, then you must implement the [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) features on the web server. (ie responding to the `OPTIONS` preflight request, and return the appropriate `Access-Control-*` headers. It's a big topic but MDN has a good resource on this.

If you're trying to use ajax on a `file://` url to fetch something from the local filesystem, you'll need [cordova-plugin-wkwebiew-xhr-fix](https://github.com/oracle/cordova-plugin-wkwebview-file-xhr) plugin.

If your app release is not urgent, you may want to consider waiting a few days to see if `cordova-ios@6` is released (currently in the voting process), so you can take advantage of custom schemes, which should make the xhr fix plugin redundant, and you also won't need this plugin since it incorporates wkwebview into its core.

**Comment by Developer3010** [comment]
The app is quite urgent, so I implemented ajax calls with CORS options.
Thanks a lot to everyone for the support!

**Comment by breautek** [comment]
Great! Can this issue be closed now?
