### ISSUE TITLE
WKWebview suspend immediately in background

### ISSUE THREAD

**Issue by vukhacbiet** [apache/cordova-plugin-wkwebview-engine#156]
# Bug Report

## Problem

In iOS, Webview suspend immediately, before the content can be back after "overscroll"

## Information

I tested in my iPhone X, iOS 13.5 with Hello Cordova app

![image](https://user-images.githubusercontent.com/43400653/83348566-2ddb0780-a358-11ea-973a-b94e0fdb01e4.png)
I scroll to top of the app and swipe up from bottom to go to App Switcher iOS

![image_720](https://user-images.githubusercontent.com/43400653/83348567-30d5f800-a358-11ea-8891-c92d08d68925.png)
Default Top Position 

### Environment, Platform, Device
iOS 13.5 - iPhone X 

### Version information

> Cordova Platforms: ios 5.1.1
> cordova-plugin-wkwebview-engine 1.2.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
