### ISSUE TITLE
Cookie with WKWebView are not persistent

### ISSUE THREAD

**Issue by Developer3010** [apache/cordova-plugin-wkwebview-engine#160]
# Bug Report

Hi, I recently migrated to WKWebView since UIWebView has been deprecated.
With the new view I am having a lot of problems, especially regarding cookies during ajax calls, which are not maintained and consequently I cannot login to my app.
Can anyone tell me if they can somehow be saved so that the session_id is always the same and does not change with every single call?

## Problem

to log in to my app I need cookies to be saved, without those the call to the server fails because the session is not set, given that with each call the PHPSESSID is different

### What is expected to happen?

I expect cookies to be saved or that there is still a way to make this happen

### What does actually happen?

Noe cookie are not saved or stored, they are not persistent

### Environment, Platform, Device

iPhone 6s -> 13.4
iPhone 11 -> 13.5

xcode 11.4.1

### Version information

I'm using:;
"cordova-ios": "^5.1.1",
"cordova-plugin-wkwebview-engine": "^1.2.1"
"cordova-plugin-wkwebview-inject-cookie": "1.0.6"
## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by vedatozkanTr** [comment]
when I by removing the "cordova-plugin-wkwebview-engine" then build successfully but IOS App rejected
**Guideline 2.1 - Performance - App Completeness
We discovered one or more bugs in your app when reviewed on iPad and iPhone running iOS 13.5.1 on Wi-Fi.

Specifically, the buttons in the app were unresponsive.**

I have been looking at the forums for a long time but there is no solution. Cordova crash !!!!!!!
I think it's time to cross over to Xamarin. Nobody is interested.

cordova cli 9.0
cordova platform add ios@6.1.0

**Comment by sjoerdloeve** [comment]
I was facing a similar problem earlier and then found out that the cordova-plugin-inappbrowser was causing the trouble..
Do you use this plugin as well? 

By adding the option `clearcache=no` the problem was solved for me.
See https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-inappbrowser/#cordovainappbrowseropen for more information.

**Comment by devjva** [comment]
Same

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
