### ISSUE TITLE
Confirming cordova-ios version

### ISSUE THREAD

**Issue by Pratz007-tech** [apache/cordova-plugin-wkwebview-engine#167]
I currently have cordova-ios : 5.1.1 after installation of this plugin few other plugins are getting crashed. Once i uninstall it app is simulated properly.  

Also , Will this plugin not work with cordova-ios latest version i.e 6.1.0 ? 

Thanks & Regards,
Pratiksha

**Comment by lovelyelfpop** [comment]
For cordova-ios@6.0.0+, the cordova-plugin-wkwebview-engine plugin is obsolete and will not work with this release. If you have this plugin installed, it is safe to remove with cordova plugin remove cordova-plugin-wkwebview-engine.
So is cordova-plugin-splashscreen for cordova-ios@6.0.0+

**Comment by timbru31** [comment]
Please refer to our recent blog post where all your questions have been answered: https://cordova.apache.org/howto/2020/07/18/uiwebview-warning.html
