### ISSUE TITLE
installing plugin results in MyApplication platform being installed

### ISSUE THREAD

**Issue by sts-ryan-holton** [apache/cordova-plugin-wkwebview-engine#168]
# Bug Report

## Problem

When trying to install the package using `cordova plugin add cordova-plugin-wkwebview-engine` from within a Cordova based project with several platforms the plugin tries to create a **MyApplication** platform instead of updating the iOS platform?

### What is expected to happen?

It should install into iOS platform

### What does actually happen?

An error is being shown and it's creating a **MyApplication** platform which isn't what I intend this plugin to be used for, it should be modifying the iOS platform right?

<img width="1434" alt="Screenshot 2020-07-25 at 11 59 08" src="https://user-images.githubusercontent.com/25177538/88455590-74d40d80-ce6e-11ea-9a08-0e07fa7e4e34.png">

### Command or Code

```bash
cordova plugin add cordova-plugin-wkwebview-engine
```

### Environment, Platform, Device

Mac OS

### Version information

Node JS: 10.15.3
NPM: 6.14.2
Cordova: 9.0.0
Xcode: 11.6

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
As you can see in the first line of your screenshot, the platform „MyApplication“ is already registered, hence this plugin tried to add support for it, too. And obvious fails.

But this is not caused by the wkwebview plugin, something else has messed up your platforms.
I’ll try to search your folders with your favorite editor or IDE for this strange string to see where it originated from.

**Comment by timbru31** [comment]
You could also delete all the platforms and plugins folder, re-add the iOS (and other platforms) and then re-install this plugin.

**Comment by sts-ryan-holton** [comment]
@timbru31 I find that to be a little difficult to believe. I've done a search for **MyApplication** in my `cordova` folder, and the only references to this are the ones that this plugin tried to install. If I delete **MyApplication** from my `platforms` folder and re-add the plugin, it simply installs a **MyApplication** folder.

Surely this isn't right?
<img width="343" alt="Screenshot 2020-07-25 at 12 57 21" src="https://user-images.githubusercontent.com/25177538/88456575-730e4800-ce76-11ea-8830-23246878beb4.png">


<img width="1051" alt="Screenshot 2020-07-25 at 12 57 32" src="https://user-images.githubusercontent.com/25177538/88456570-70135780-ce76-11ea-9af9-b07b2e6199dd.png">

**Comment by timbru31** [comment]
As you can see the `MyPlatform` platform is already present - this has nothing to do with this plugin. (as you can see by running a search for on GitHub for this string. Either your config.xml has an invalid platform called `MyApplication` or another plugin adds this faulty platform.
