### ISSUE TITLE
ios 13.6 and the new wkwebview engine

### ISSUE THREAD

**Issue by aubrey-fowler** [apache/cordova-plugin-wkwebview-engine#170]
Since I have updated my app to the wkwebview engine, my footer buttons on ionic no longer work and can be pushed down out of the safe zone of the app.

See also: https://stackoverflow.com/questions/63303752/ionic-cordova-ios-12-and-13-pushing-footer-buttons-beyond-safe-area/63343385#63343385

```
ionic info

Ionic:

   ionic (Ionic CLI) : 4.10.3 (C:\Users\User\node_modules\ionic)
   Ionic Framework   : ionic1 1.3.5
   @ionic/v1-toolkit : 1.0.22

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 8.1.0, ios 6.1.0, browser 5.0.4, windows 4.4.3
   Cordova Plugins       : cordova-plugin-ionic-webview 4.1.3, (and 17 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\User\Documents\Android\sdk)
   NodeJS            : v10.21.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.4
   OS                : Windows 10
```

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by timbru31** [comment]
Besides that, it seems you are using the fork cordova-plugin-ionic-webview, so you need seek support with/from Ionic.
