### ISSUE TITLE
Freezing application when add this plugin 

### ISSUE THREAD

**Issue by touficy** [apache/cordova-plugin-wkwebview-engine#174]
###  BUG 
Freezing application when add this plugin 
 
###  What is expected to happen?

    application workflow successfully on "  ios " 

###  What does actually happen?

 when i add this plugin the application became freezing , cant navigate to any page on " ios " , if i remove it everything work 
 successfully . but i can't upload it without this plugin because apple support wkWebview

 
### Command or Code
    config xml : 
   <content src="index.html"/>
  <allow-navigation href="*"/>
  <allow-intent href="itms:*"/>
  <allow-intent href="itms-apps:*"/>
  <preference name="loglevel" value="DEBUG"/>
  <preference name="AndroidLaunchMode" value="singleTop"/>
  <preference name="ErrorUrl" value=""/>
  <preference name="SplashScreen" value="screen"/>
  <preference name="AllowInlineMediaPlayback" value="false"/>
  <preference name="BackupWebStorage" value="cloud"/>
  <preference name="FadeSplashScreenDuration" value="250"/>
  <preference name="KeyboardDisplayRequiresUserAction" value="true"/>
  <preference name="MediaPlaybackRequiresUserAction" value="false"/>
  <preference name="SuppressesIncrementalRendering" value="false"/>
  <preference name="TopActivityIndicator" value="gray"/>
  <preference name="GapBetweenPages" value="0"/>
  <preference name="PageLength" value="0"/>
  <preference name="PaginationBreakingMode" value="page"/>
  <preference name="PaginationMode" value="unpaginated"/>
  <feature name="LocalStorage">
    <param name="ios-package" value="CDVLocalStorage"/>
  </feature>
  <preference name="UIWebViewDecelerationSpeed" value="normal"/>
  <platform name="ios">
    <preference name="orientation" value="portrait"/>
    <icon src="/res/ios/icon/icon.png" width="57" height="57"/>
    <icon src="/res/ios/icon/icon@2x.png" width="114" height="114"/>
    <icon src="/res/ios/icon/icon-72.png" width="72" height="72"/>
    <icon src="/res/ios/icon/icon-72@2x.png" width="144" height="144"/>
    <icon src="/res/ios/icon/icon-60.png" width="60" height="60"/>
    <icon src="/res/ios/icon/icon-60@2x.png" width="120" height="120"/>
    <icon src="/res/ios/icon/icon-60@3x.png" width="180" height="180"/>
    <icon src="/res/ios/icon/icon-76.png" width="76" height="76"/>
    <icon src="/res/ios/icon/icon-76@2x.png" width="152" height="152"/>
    <icon src="/res/ios/icon/icon-40.png" width="40" height="40"/>
    <icon src="/res/ios/icon/icon-40@2x.png" width="80" height="80"/>
    <icon src="/res/ios/icon/icon-50.png" width="50" height="50"/>
    <icon src="/res/ios/icon/icon-50@2x.png" width="100" height="100"/>
    <icon src="/res/ios/icon/icon-small.png" width="29" height="29"/>
    <icon src="/res/ios/icon/icon-small@2x.png" width="58" height="58"/>
    <icon src="/res/ios/icon/icon-small@3x.png" width="87" height="87"/>
    <icon src="/res/ios/icon/icon-83.5@2x~ipad.png" width="167" height="167"/>
    <icon src="/res/ios/icon/icon-1024.png" width="1024" height="1024"/>
    <splash src="/res/ios/screen/Default@2x~universal~anyany.png"/>
    <preference name="AllowUntrustedCerts" value="on"/>
    <preference name="InterceptRemoteRequests" value="all"/>
    <preference name="NativeXHRLogging" value="full"/>
    <edit-config target="NSLocationWhenInUseUsageDescription" file="*-Info.plist" mode="merge">
      <string>need location access to find things nearby</string>
    </edit-config>
    <config-file parent="NSBluetoothAlwaysUsageDescription" platform="ios" target="*-Info.plist">
      <string>Bluetooth permission is required because of X, Y and Z</string>
    </config-file>
    <config-file parent="NSCameraUsageDescription" platform="ios" target="*-Info.plist">
      <string>Camera is used for scanning barcode</string>
    </config-file>
    <config-file parent="NSPhotoLibraryUsageDescription" platform="ios" target="*-Info.plist">
      <string>You can upload your profile picture using your Photo Library</string>
    </config-file>
    <config-file parent="NSLocationAlwaysUsageDescription" platform="ios" target="*-Info.plist">
      <string>You can upload your profile picture using your Photo Library</string>
    </config-file>
    <config-file platform="ios" parent="CFBundleLocalizations" target="*-Info.plist">
      <array>
        <string>en</string>
      </array>
    </config-file>
    <preference name="WKWebViewOnly" value="true"/>
    <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine"/>
    <feature name="CDVWKWebViewEngine">
      <param name="ios-package" value="CDVWKWebViewEngine"/>
    </feature>
  </platform>
  <platform name="android">
    <preference name="android-minSdkVersion" value="19"/>
    <preference name="android-targetSdkVersion" value="29"/>
    <preference name="android-targetSdkVersion" value="29"/>
    <icon src="/res/android/icon/ldpi.png" density="ldpi"/>
    <icon src="/res/android/icon/mdpi.png" density="mdpi"/>
    <icon src="/res/android/icon/hdpi.png" density="hdpi"/>
    <icon src="/res/android/icon/xhdpi.png" density="xhdpi"/>
    <icon src="/res/android/icon/xxhdpi.png" density="xxhdpi"/>
    <icon src="/res/android/icon/xxxhdpi.png" density="xxxhdpi"/>
    <splash src="/res/android/screen/splash-port-ldpi.png" density="port-ldpi"/>
    <splash src="/res/android/screen/splash-port-xhdpi.png" density="port-xhdpi"/>
    <splash src="/res/android/screen/splash-port-xxhdpi.png" density="port-xxhdpi"/>
    <splash src="/res/android/screen/splash-port-xxxhdpi.png" density="port-xxxhdpi"/>
    <splash src="/res/android/screen/splash-mdpi.png" density="mdpi"/>
    <splash src="/res/android/screen/splash-port-mdpi.png" density="port-mdpi"/>
    <splash src="/res/android/screen/splash-port-hdpi.png" density="port-hdpi"/>
  </platform>
  <preference name="WindowsStorePublisherName" value="My Name"/>
  <preference name="WindowsStoreIdentityName" value="9114f65e-a2cb-b6ec-e1c0-626d14a47905"/>
  <config-file target="*-Info.plist" parent="LSApplicationQueriesSchemes">
    <array>
      <string>ebdaauserapp</string>
    </array>
  </config-file>
  <platform name="electron">
    <icon src="/res/electron/icon/icon_electron_512.png" width="512" height="512"/>
    <preference name="SplashScreenWidth" value="620"/>
    <preference name="SplashScreenHeight" value="300"/>
    <preference name="ShowSplashScreen" value="false"/>
    <splash src="/res/electron/screen/electron_splash_image.png" width="620" height="300"/>
  </platform>
  <preference name="ios-XCBuildConfiguration-TARGETED_DEVICE_FAMILY" value="1,2"/>
  <preference name="AutoHideSplashScreen" value="true"/>
  <preference name="FadeSplashScreen" value="true"/>
  <preference name="ShowSplashScreenSpinner" value="false"/>
  <preference name="EnableViewportScale" value="true"/>
  <edit-config target="NSCameraUsageDescription" file="*-Info.plist" mode="merge">
    <string>need camera access to take pictures</string>
  </edit-config>
  <edit-config target="NSMicrophoneUsageDescription" file="*-Info.plist" mode="merge">
    <string>need microphone access to record sounds</string>
  </edit-config>
  <edit-config target="NSPhotoLibraryUsageDescription" file="*-Info.plist" mode="merge">
    <string>need to photo library access to get pictures from there</string>
  </edit-config>
  <edit-config target="NSLocationWhenInUseUsageDescription" file="*-Info.plist" mode="merge">
    <string>need location access to find things nearby</string>
  </edit-config>
  <edit-config target="NSPhotoLibraryAddUsageDescription" file="*-Info.plist" mode="merge">
    <string>need to photo library access to save pictures there</string>
  </edit-config>
  <access origin="*"/>
  <preference name="KeepRunning" value="true"/>
  <preference name="monaca:AndroidIsPackageNameSeparate" value="false"/>
  <preference name="DisallowOverscroll" value="true"/>
  <preference name="Orientation" value="portrait"/>
  <preference name="SplashScreenDelay" value="5000"/>
  <preference name="Fullscreen" value="false"/>
</widget>

### Environment, Platform, Device
 this is issue on all ios system mobile application

### What are relevant versions you are using?
Cordova: 

- work on cordova  ios platform 5.0.1

-built environment ios platform ---> 5.1.1

-built environment ios Xcode---> 11.3

Other Frameworks: 

- framework7 mobile ( https://framework7.io/docs/ ) 

- Monaca: Cloud-Powered HTML5 Hybrid Mobile App  to upload app to Xcode ( https://console.monaca.mobi/dashboard )

### plugin i have 

1. cordova-plugin-app-version

2. cordova-plugin-call-number

3. cordova-custom-config

4. cordova-plugin-device

5. monaca-plugin-monaca-core

6. onesignal-cordova-plugin

7. cordova-plugin-splashscreen

8. cordova-plugin-whitelist

9. cordova-plugin-wkwebview-engine

 

## Checklist
 
- [ x ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
-  [ x ] I included all the necessary information above

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
