### ISSUE TITLE
postMessage() in WKWebView 

### ISSUE THREAD

**Issue by freescout-helpdesk** [apache/cordova-plugin-wkwebview-engine#175]
In UIWebView we are using `webkit.messageHandlers.cordova_iab.postMessage()` to post messages. 

And to listen to messages:
```
inappbrowser.addEventListener('message', function (params) {
    ....
});
```

In WKWebView we need to use webkit.messageHandlers.**cordova**.postMessage()?

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
