### ISSUE TITLE
Fail to compile CDVWKWebViewEngine.o to CDVWKWebViewEngine.m normal arm64 objective-c

### ISSUE THREAD

**Issue by Pitouli** [apache/cordova-plugin-wkwebview-engine#177]
# Bug Report

### What is expected to happen?

My app should build

### What does actually happen?

```
** ARCHIVE FAILED **

The following build commands failed:
        CompileC /Users/pitouli/Library/Developer/Xcode/DerivedData/MyApp-hcczzqafauzxokbhoszenxnbgkca/Build/Intermediates.noindex/ArchiveIntermediates/Kipinto/IntermediateBuildFilesPath/Kipinto.build/Release-iphoneos/MyApp.build/Objects-normal/arm64/CDVWKWebViewEngine.o /Users/pitouli/Documents/GIT/MyApp/cordova/platforms/ios/MyApp/Plugins/cordova-plugin-wkwebview-engine/CDVWKWebViewEngine.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

## Information

If I remove the plugin, then the installation succeeds.
Or if I downgrade cordova-ios to 5.1.1; it succeeds (note: it fails on 6.0.0)

### Command or Code

Run: 

```
cordova create MyApp
cd MyApp
cordova plugin add cordova-plugin-wkwebview-engine --save
cordova platform add ios
cordova build ios
```

You should have signing errors. Open Xcode to parameter the correct provisioning profiles.
And relaunch `cordova build ios`

You should observe the exact same error as above.

Note: my package looks like this:

```
{
  "name": "io.cordova.hellocordova",
  "displayName": "HelloCordova",
  "version": "1.0.0",
  "description": "A sample Apache Cordova application that responds to the deviceready event.",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "ecosystem:cordova"
  ],
  "author": "Apache Cordova Team",
  "license": "Apache-2.0",
  "devDependencies": {
    "cordova-ios": "^6.1.1",
    "cordova-plugin-whitelist": "^1.3.4",
    "cordova-plugin-wkwebview-engine": "^1.2.1"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-wkwebview-engine": {}
    },
    "platforms": [
      "ios"
    ]
  }
}

```
### Environment, Platform, Device

MacOS 10.15.6, XCode 12.0.1, 

### Version information

Cordova: Cordova CLI 10.0, Cordova-iOS 6.1.1, 

Plugins:
cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine"

## Checklist

- [x] I searched for existing GitHub issues (and stackoverflow)
- [x] I updated all Cordova tooling to most recent version (and technically the issue arrived then)
- [x] I included all the necessary information above (hopefully)

**Comment by erisu** [comment]
Uninstall this plugin when using Cordova-iOS 6.x. It already uses WKWebView.

**Comment by brodybits** [comment]
We have added the needed restriction in PR #158, and this should be released in the near future.
