### ISSUE TITLE
RBSAssertionErrorDomain, file picker

### ISSUE THREAD

**Issue by ptorrent** [apache/cordova-plugin-wkwebview-engine#179]
Hello there,

I'm using cordova 10.0.0,
cordova IOS 5

When I want to pick a file with <input type="file" and I try to send the file to my server,

I'm ussing FormData in XMLHttpRequest to send the file.

I've got this error message:

RBSAssertionErrorDomain; code : 2 ; reason : "Client is missing required entitlement". 

Is there a link between cordova-plugin-wkwebview-engin and this issue ?

Thanks for your support

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
