### ISSUE TITLE
The sandbox is not in sync with the podfile.lock run pod install or update cocoapods installation - ionic v5 ios

### ISSUE THREAD

**Issue by prabhashibuddhima** [apache/cordova-plugin-wkwebview-engine#180]
# Bug Report

### What is expected to happen?
app build should be success

### What does actually happen?
app build failed

## Information

I have run the following commands to my ionic v5 app. (please note that I added 

```
<preference name="WKWebViewOnly" value="true" />
<feature name="CDVWKWebViewEngine">
  <param name="ios-package" value="CDVWKWebViewEngine" />
</feature>

<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
```
to my config.xml )

`npm install`
`ionic cordova platform add ios@5.1.1`
`cordova plugin add cordova-plugin-wkwebview-engine`
`ionic cordova prepare ios`
`ionic cordova build ios`

and then the following error message showing to me .

`error : linker command failed with exit code 1`

then I tried installing

`sudo gem install cocoapods` --> in app directory
`pod install` --> in platforms/ios
`pod repo update` --> in app directory

then I tried to build my app again by

`ionic cordova build ios`

then I got the following error:

```
diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

### Environment, Platform, Device

ionic ios

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
