### ISSUE TITLE
Fixed header/nav bar flickering on keyboard pop up due to webview resize

### ISSUE THREAD

**Issue by sajallimbu** [apache/cordova-plugin-wkwebview-engine#181]
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Description
I have an app with a fixed navbar on top. I have some text field in the page. When i focus on the text field, the keyboard pops up and pushes the view up slightly. What my problem is that it pushes the whole webview up so that my fixed navbar on top gets pushed top as well. But since the navbar is fixed to top of the webview. It tries to come back to it's position and it's shows as flickering. How can i stop this? How to make it so that only the page is pushed and not the fixed navbar.

**Comment by timbru31** [comment]
This seems like this WebKit bug you are describing: https://github.com/apache/cordova-ios/issues/417, it's fixed in iOS 13.4, for <iOS 13.4 you can try the cordova-plugin-wkkeyboardfix plugin. For the next time, please fill in the issue template and do not delete important sections, thanks :)

**Comment by wswoodruff** [comment]
Adding the `cordova-plugin-wkkeyboardfix` hasn't fixed the whitespace issue for me
