### ISSUE TITLE
M1 Macbook cant build ios app with WKWebView

### ISSUE THREAD

**Issue by yahyaisfast** [apache/cordova-plugin-wkwebview-engine#183]
# Bug Report

## Problem
The new M1 Macbook is having an issue where I can't compile the ios build due to the WKWebView plugin. It mentions how the plugin requires x64 or x86 but since the Silicon chip is ARM based it will not build.

### What is expected to happen?
The ios build should be able to build the application in WKWebView.

### What does actually happen?
I get an error 65 xcodebuild.

## Information

Build program on M1 macbook using WKWebView Plugin installed.

### Command or Code

cordova build ios

### Environment, Platform, Device

M1 Macbook Pro 2020

### Version information

Cordova CLI: Latest Version
Cordova platforms: ios
Cordova plugins: cordova-plugin-wkwebview-engine
Operating: XCode

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Can M1 macs build `cordova-ios@6` without this plugin? If you could give this a try that would be awesome.

**Comment by francois-n-dream** [comment]
I have a M1 2020 and wasn't able to build either. This was however not because of the M1 but because cordova-6+ doesn't work with this plugin. At least I found it written here: https://cordova.apache.org/announcements/2020/06/01/cordova-ios-release-6.0.0.html

Compiling after removing this plugin worked.

**Comment by breautek** [comment]
> I have a M1 2020 and wasn't able to build either. This was however not because of the M1 but because cordova-6+ doesn't work with this plugin. At least I found it written here: https://cordova.apache.org/announcements/2020/06/01/cordova-ios-release-6.0.0.html
> 
> Compiling after removing this plugin worked.

Correct, this plugin does not support Cordova-ios 6 because cordova-ios 6 uses WKWebView in it's core, since Apple now disallows usage of the old UIWebView.

I'm going to guess the OP also was trying to use this on the latest cordova-ios so I'll be closing this issue.
