### ISSUE TITLE
v1.2.2 update needs to be synced to npm (currently v1.2.1)

### ISSUE THREAD

**Issue by jimbergman** [apache/cordova-plugin-wkwebview-engine#185]
A gentle reminder to please update npm with this release so it can be pulled from config.xml

[https://www.npmjs.com/package/cordova-plugin-wkwebview-engine](https://www.npmjs.com/package/cordova-plugin-wkwebview-engine)

Thanks!

**Comment by breautek** [comment]
It's being voted on. The vote will be closing soon and (as it currently stands at the time of writing) the release will continue and be published on NPM.

But if someone ends up voting to reject, then the release may be delayed or 1.2.2 may not even make it to NPM.
