### ISSUE TITLE
iphone x

### ISSUE THREAD

**Issue by seb64** [apache/cordova-plugin-wkwebview-engine#48]
on iphone X viewport is set to 354x724 instead of 375x812
css rules fail to determine it's iphone x
when AdMob.showBanner is called viewport switches to correct values

**Comment by janpio** [comment]
This problems only occurs when using `cordova-plugin-wkwebview-engine`, not with the default (UI)webview?

**Comment by seb64** [comment]
It's working now and I can't find the reason. I even works without viewport-fit=cover.
The only plausible explanation is that reinstalling the plugin did the trick.

**Comment by janpio** [comment]
Best bugs are those that solves themselves 🥇

**Comment by mwargan** [comment]
I'm experiencing a similar issue where the height is incorrect on launch, but is corrected when I rotate the screen to landscape and back to portrait. Unfortunately, it's not resolving itself :/
