### ISSUE TITLE
Scroll to top for bottom TextField not working.

### ISSUE THREAD

**Issue by vishal-iosdeveloper** [apache/cordova-plugin-wkwebview-engine#50]
Hi,
I had tried this plugin for one of my Project.
It is working well but one of issue that I am getting is when my Input element is at bottom, My page isn't scroll it up.
Anybody with same issue?
It'll be great if I can any have solution or help of it.

**Comment by janpio** [comment]
What platform?
What version of the plugin and Cordova CLI and Cordova platform are you using?
What is the code to reproduce this?

**Comment by Vishaliphone** [comment]
Platform : iOS

Here is a version detail : 
<plugin name="cordova-plugin-wkwebview-engine" spec="^1.1.4" />

Cordova CLI version : 
8.0.0

regarding reproduce : 
There isn't any code for it. I just installed plugin in my project. If i tap on bottom Input type, Content size is appropriately increased but my page isn't scrolled up properly. My input is still under keyboard.

**Comment by Vishaliphone** [comment]
Okay.
As you asked about code for reproduce it,
So, I updated about it.
Will try this plugin with fresh new project & update you.
Thanks !

**Comment by janpio** [comment]
(I added \` around the code in your previous comment so the XML is actually visible)

**Comment by WuglyakBolgoink** [comment]
@Vishaliphone is it work correct without plugin?

**Comment by Vishaliphone** [comment]
Without plugin,
Input fields are going on top properly,
But my fixed headers are scrolling throughout.
So I moved here.

**Comment by sadikyalcin** [comment]
I just replicated this too. The view does not auto scroll to the focused element. I had come across similar behaviour on android which will demonstrate what we mean. Sorry but I do not have the time to create you a test project.

https://stackoverflow.com/questions/52718697/android-keyboard-covering-and-moving-input-elements-off-screen

```
<html lang="en">
<head>
<style>
  html,
  body {
    height: 100%;
    position: relative;
  }

  input {
    position: absolute;
    bottom: 50px;
  }
</style>
</head>
<body>
  <div>
    <input type="text" placeholder="Test"></input>
  </div>
</body>
</html>
```

**Comment by burtontanner** [comment]
Same here in 2020.

**Comment by burtontanner** [comment]
removing cordova-plugin-keyboard solved my issue.

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
