### ISSUE TITLE
iPhone X initial height issue

### ISSUE THREAD

**Issue by mwargan** [apache/cordova-plugin-wkwebview-engine#53]
I'm experiencing an issue where the height is incorrect on launch, but is corrected when I rotate the screen to landscape and back to portrait.
![img_1574](https://user-images.githubusercontent.com/13789481/44619440-c0e33580-a886-11e8-844e-0c48ae8e345c.PNG)

**Comment by janpio** [comment]
What iOS version are you running on this device?
Is the problem also present in other, older iOS versions?

If this is iOS 11: Does the framework you are using support it?

**Comment by mwargan** [comment]
@janpio this is iOS12 Beta, haven't tested with older versions just yet - will try now... I'm running Framework 7 with VueJS 2 and Cordova 8

**Comment by mwargan** [comment]
iOS 10 11 and 12 same issue. In the browser its fine, its Cordova related <-- thats also what they told me at the Framework 7 Issues on GitHub...

When I uninstall this engine this issue does not present itself on load...

**Comment by mwargan** [comment]
I’ll try the ionic WebView this evening - but my project doesn’t use ionic - won’t that be an issue?

Upon further investigation, when I uninstall this plugin the issue with the bottom white space is removed and the Navbar displays correctly. Upon rotating and going back again the Navbar then looks like on the screen above - so in essence uninstalling this plugin partly reversed the problem.


https://github.com/framework7io/framework7/issues/2600 <— that’s the framework 7 issue though it was relating to another problem (that coincidentally I was hoping this one would solve, but I had to get the keyboard plugin).

**Comment by janpio** [comment]
> I’ll try the ionic WebView this evening - but my project doesn’t use ionic - won’t that be an issue?

It's just an experiment to try to find out what is going on - but the plugin is a normal Cordova plugin that is made by Ionic people. It should work fine.

**Comment by mwargan** [comment]
Ok so I wasn't able to get Ionic working at all with my project, but have figured out that I was facing two issues. The status bar I managed to fix, so it displays correctly. However, the white space still remains. When I remove this plugin the issue disappears. Any ideas on where/what to look for to further debug?

**Comment by lukeinage** [comment]
I also have this issue, even after trying the fix from https://github.com/apache/cordova-plugin-wkwebview-engine/pull/45 

It still appears to be using the incorrect height on initial load.

**Comment by mwargan** [comment]
I've noticed that either changing the orientation or opening and closing the keyboard 'fixes' this issue...

**Comment by lukeinage** [comment]
Turns out my issue was with the inappbrowser-wkwebview instead which makes use of this plugin https://github.com/dpa99c/cordova-plugin-inappbrowser-wkwebview

It's the same fix as #45 and I added it to line 612 of CDVInAppBrowser.m

`#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 110000
   if (@available(iOS 11.0, *)) {
       [self.webView.scrollView setContentInsetAdjustmentBehavior:UIScrollViewContentInsetAdjustmentNever];
   }
#endif`

**Comment by janpio** [comment]
Did you open a PR for that plugin @lukeinage? Seems worth moving over there as well then.

**Comment by mwargan** [comment]
I can confirm that https://github.com/apache/cordova-plugin-wkwebview-engine/pull/45 worked for me 👍 (I wasn't using inappbrowser-wkwebview, I just implemented the fix directly)!

**Comment by lukeinage** [comment]
@janpio Yes, that's in inappbrowser wkwebview now 👍

**Comment by mwargan** [comment]
My issue was related to #45 which has now been merged - so closing ;)

**Comment by davidjeliba** [comment]
#45 solved this issue for me as well however it seems to have only been merged into master without a release so I had to manually change the local library as apache/cordova-plugin-wkwebview-engine is a dependency of oracle/cordova-plugin-wkwebview-file-xhr but it will fetch version 1.1.4 (not master) which does not contain the fix.

**Comment by benmcmaster** [comment]
[#45](https://github.com/apache/cordova-plugin-wkwebview-engine/pull/45) also solved my issue. I am building from the commit on github, but it would be awesome to get it into a release! Any idea when that will be? Thanks!

**Comment by jacobweber** [comment]
Yes, can we get this in a release? I spent a day trying to figure this out. I also got 1.1.4 via cordova-plugin-wkwebview-file-xhr.

**Comment by xtassin** [comment]
I was very happy to finally find a solution to a problem I have been trying to solve for days only to find that fix #45 was reverted here #107

I believe this issue should be re-open and a discussion started about the best approach to fix the issue in a consensual maner.

**Comment by janpio** [comment]
We won't reopen this issue, please create a new one and link to the relevant closed PRs and issues.

**Comment by votala** [comment]
Deleting wkwebview only preference from config.xml worked for me
