### ISSUE TITLE
Cannot load `file://` html templates

### ISSUE THREAD

**Issue by j3k0** [apache/cordova-plugin-wkwebview-engine#54]
My apps loads html files as templates. I needed to add the below in order for this to work.

```
[configuration.preferences setValue:@YES forKey:@"allowFileAccessFromFileURLs"];
```

Is there any better solution than patching the plugin? Thanks

**Comment by globules-io** [comment]
https://github.com/oracle/cordova-plugin-wkwebview-file-xhr

**Comment by jcesarmobile** [comment]
this is a known WKWebView issue, you can use the mentioned file-xhr plugin, or move to cordova-ios 6 and use a custom scheme
