### ISSUE TITLE
Could not signal service com.apple.WebKit.WebContent in ios 11.4.1

### ISSUE THREAD

**Issue by nguyenhaduchieu** [apache/cordova-plugin-wkwebview-engine#55]
I used meteor and debug in ios 11.4.1. Something is error. The application is white page in device. I think we have problem in webview. Please help me.

`2018-09-13 17:41:09.912442+0700 IDLdev[1236:301325] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2018-09-13 17:41:09.913603+0700 IDLdev[1236:301325] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service`

**Comment by ugurozcan** [comment]
Hello,
I have the same problem. Did you find a solution?

**Comment by ch3tan03** [comment]
Install below plugin this will fix your problem.
cordova plugin add https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix

**Comment by mitesh-shah** [comment]
@ch3tan03 After installing this, I am getting following error.

`CDVWKWebViewEngine.h file not found`

Any idea?

**Comment by DimitrisMpanis** [comment]
Should this be included in the official cordova wkwebview plug in?

**Comment by donni106** [comment]
Any update? I am also facing `Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service` in Simulator on iOS 11.0.1. 

For iOS 13.0 there is `CDVPlugin class WKWebViewXHRFix (pluginName: wkwebviewxhrfix) does not exist.` but everything is working fine.

**Comment by pal03377** [comment]
> CDVWKWebViewEngine.h file not found

Also running `cordova plugin add cordova-plugin-wkwebview-engine` after `cordova plugin add https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix` fixed this for me.

**Comment by ch3tan03** [comment]
> @ch3tan03 After installing this, I am getting following error.
> 
> `CDVWKWebViewEngine.h file not found`
> 
> Any idea?

Add remove platform

**Comment by vousys** [comment]
remember to add this plugins:

```
<plugin name="cordova-plugin-wkwebview-engine"  source="npm" /> 
<plugin name="cordova-plugin-wkwebview-file-xhr"  source="npm" />
``` 
and add this

```
<preference name="WKWebViewOnly" value="true" />
<feature name="CDVWKWebViewEngine">
    <param name="ios-package" value="CDVWKWebViewEngine" />
</feature>
<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
<preference name="AllowBackForwardNavigationGestures" value="true" />
<preference name="Allow3DTouchLinkPreview" value="false" />
```
And compile with cordova-ios@5.1.1+

**Comment by ss15408it2015** [comment]
after adding <plugin name="cordova-plugin-wkwebview-file-xhr"  source="npm" />
worked for me in local

**Comment by andersoonluan** [comment]
> Install below plugin this will fix your problem.
> cordova plugin add https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix

this really worked for me! thanks a lot!

**Comment by klochko7** [comment]
Good day! Could anyone suggest please ..  Ioinc 5 app crashed ...

`Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service`

Installed platforms ios 6.1.1, 

add plugin https://github.com/apache/cordova-plugin-wkwebview-engine 

add `preference name="WKWebViewOnly" value="true" `

Software version 12.5.1

**Comment by MarcelSchuermann** [comment]
I have the same issue with cordova 10.0.0 ios platform 6.2.0 without using this plugin - see following issue:

[https://stackoverflow.com/questions/67571345/ios-iphone-11-flashing-black-and-white-while-browsler-is-constantly-reloading-r](https://stackoverflow.com/questions/67571345/ios-iphone-11-flashing-black-and-white-while-browsler-is-constantly-reloading-r)

This plugin should not be used with cordova-iOS > 6, right?
Any ideas how to fix this?

**Comment by breautek** [comment]
> This plugin should not be used with cordova-iOS > 6, right?

Correct, cordova-ios@6 implements the WKWebView itself as required by Apple's policies.

White page usually signals a javascript exception that has occurred. You can use the Safari web inspector ([learn how](https://breautek.com/articles/debugging-cordova-apps.html)) to check for javascript errors. Safari doesn't record errors that occurred before the inspector was attached, therefore you'll need to refresh the webview to see startup errors. You can do this by pressing `cmd` + `R` while the inspector is focused.

Cordova itself also doesn't do any kind of reloading on error, so this is likely behaviour coming from an external code, such as a framework, library, or perhaps even your own application.

**Comment by MarcelSchuermann** [comment]
@breautek Thanks for your reply.
In the emulator there is no error so I see no log in the Safari Web Inspector.
Is the inspector also accessible on real iOS devices? (I cannot test it at the moment because I currently have no Iphone 11 PRO available) - do I need that extra Safari Preview Browser?

**Comment by breautek** [comment]
> @breautek Thanks for your reply.
> In the emulator there is no error so I see no log in the Safari Web Inspector.
> Is the inspector also accessible on real iOS devices? (I cannot test it at the moment because I currently have no Iphone 11 PRO available) - do I need that extra Safari Preview Browser?

You can use an inspector on physical devices, provided that the debug variant of the app is published on the device. This means the device will need to be added as a Test device on your developer account with Apple so that you can use XCode to build and install onto that device.

Sometimes the release version of Safari on the Mac is behind on the iOS Safari running on the device, particularly if you're using a recently released iOS version which may be incompatible for remote debugging.  **Usually** in these cases, you can use [Safari Tech Preview](https://developer.apple.com/safari/technology-preview/) version of Safari to remote debug your webview.

**Comment by thomstark** [comment]
There's no error in the safari console for iphone > about:blank or for iphone > [myappname]. about:blank is just an empty html page and [myappname] is the content of my cordova app, not the inappbrowser window.

**Comment by thomstark** [comment]
and i have cordova-plugin-wkwebviewxhrfix and have had for over a year now.

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
