### ISSUE TITLE
WKwebview cannot load resources outside of app directory

### ISSUE THREAD

**Issue by guirip** [apache/cordova-plugin-wkwebview-engine#56]
Hello

I know this might not be the proper place because it may purely be a WKwebview bug, anyway if anyone has experienced this issue, knows about a possible work-around, or can point me to a more appropriate support I will be interested. Thanks.

(originally posted on [stack-overflow](https://stackoverflow.com/questions/52373061/webkit-webview-wkwebview-cannot-load-resources-outside-of-app-directory))

As **UIWebview** is now deprecated we started to use the **WKwebview**. We added `cordova-plugin-wkwebview-engine` as described here: https://cordova.apache.org/news/2018/08/01/future-cordova-ios-webview.html (and also `cordova-plugin-wkwebview-file-xhr`)

1 - First, our app is built and shipped including assets (icons, images, etc) whose path looks like:
`file:///var/containers/Bundle/Application/[APP_ID]/[APP_NAME]/www/files/project/home/iconA.svg`

These assets are correctly displayed.

2 - Then on startup the app also checks with our backend if there is any update available. If some assets have been updated, then the app downloads them in the data directory. The path to the above asset becomes:
`file:///var/mobile/Containers/Data/Application/[APP_ID]/Library/NoCloud//V1/files/project/home/iconA.svg`

...but these assets are not displayed.

NB1: In both cases, the resource is declared in a background-image css property.
NB2: We've been using this process for years with success with the former UIwebview.

In the network panel of Safari's web inspector, the resource appears in red, with a red message indicating that an error occurred while trying to load it. There is no error code, nothing technical to help, no more specific than this fuzzy message...

I ran some tests and it appears that **the resource is present** on the file system at the given path. (Using `cordova-plugin-file` I can output the svg content).

So, first conclusion would be that the WKwebview cannot access resources outside of app directory? As anyone any information, experience to share?

Any help would be greatly appreaciated.

**Comment by guirip** [comment]
For information, issue is confirmed here : [https://bugs.webkit.org/show_bug.cgi?id=154916](https://bugs.webkit.org/show_bug.cgi?id=154916)

People are forced to develop their own work-arounds using custom url schemes... so rationally it has been requested that `cordova-ios` handles it : [https://github.com/apache/cordova-ios/issues/415](https://github.com/apache/cordova-ios/issues/415)

**Comment by dganzella** [comment]
Yes. It can't. A workaround to this is to copy the files to temp directory. It can open from /temp for some reason.

**Comment by rastafan** [comment]
Has anyone found a solution that does not involve losing support for iOS10 and lower?

**Comment by mirrorlink** [comment]
> Has anyone found a solution that does not involve losing support for iOS10?

A workaround to this is to copy the files to temp directory. It can open from /temp for some reason.

**Comment by rastafan** [comment]
> > Has anyone found a solution that does not involve losing support for iOS10?
> 
> A workaround to this is to copy the files to temp directory. It can open from /temp for some reason.

Thank you. Unfortunately, we have situations in which our clients have a lot of images on their devices, and copying them to /temp every time the app starts or the images are shown seems to be quite an heavy and time consuming task.

**Comment by sajallimbu** [comment]
Any solution for this yet?

**Comment by guirip** [comment]
There are workarounds, see [cordova-ios/issues/415](https://github.com/apache/cordova-ios/issues/415)

But finally we removed all the code related to custom url scheme management and now use [**cordova-plugin-ionic-webview**](https://github.com/ionic-team/cordova-plugin-ionic-webview) which solves the issue for us. The plugin bundles a local web server, and manages a custom url scheme (ionic://) on iOS.

**Comment by jcesarmobile** [comment]
this is a known WKWebView issue when using file:// protocol to load apps, it can't be fixed, but you can now move to cordova-ios 6 and use a custom scheme

**Comment by kapilrc** [comment]
Remove below preference from config.xml
```
<preference name="scheme" value="app" />
<preference name="hostname" value="localhost"  /> 
```

And use below plugin

`cordova plugin add https://github.com/AraHovakimyan/cordova-plugin-wkwebviewxhrfix`

this works seamlessly with Cordova iOS 6.x.x & node v10.0.0
