### ISSUE TITLE
`cdvfile` support

### ISSUE THREAD

**Issue by zhanghuanchong** [apache/cordova-plugin-wkwebview-engine#57]
Now it will report error:

> Failed to load resource: unsupported URL

when using `cdvfile` with WKWebView. Same problem see https://stackoverflow.com/questions/42760400/unsupported-url-error-for-a-cdvfile

Do you have any plan to support it?

**Comment by manusis** [comment]
Any update on this issue. We want to load local Cordova.js from remote URL.

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
