### ISSUE TITLE
Two versions of localStorate

### ISSUE THREAD

**Issue by aidanas** [apache/cordova-plugin-wkwebview-engine#58]
Just leaving this here for anyone using this plugin and having issues with localStorage not being consistent between page navigations (location.href changes). We were having this issue for quite a while in our app and as a workaround (hack) opted in to save entire localStorage to sqlite and restore from it when the next page loads. There might be already a ticket for the issue on the [issue tracker](https://issues.apache.org/jira/browse/CB-14180?jql=project%20%3D%20CB%20AND%20labels%20%3D%20wkwebview-known-issues) and possibly a solution how to avoid this condition but on a quick search I could not find one there.

I tested the case in isolation on a simple cordova  [(HelloWorld app)](https://github.com/aidanas/wkwebview-plugin-demo) and was able to recreate the problem on and iOS 9.3, iOS 10.2 but not on iOS 12.

**Comment by jcesarmobile** [comment]
since the files are loaded from file protocol, the webview can think the origin changed and cause this problem.
now you can move to cordova-ios 6 and use a custom scheme, that way the origin won't change and you won't have this problem

**Comment by aidanas** [comment]
@jcesarmobile, would you please elaborate what you mean by _"use a custom scheme"_? Do you mean using `cordova-plugin-customurlscheme` ?

**Comment by jcesarmobile** [comment]
Please, don’t ping me.
And please, read the cordova iOS 6 release notes
https://cordova.apache.org/announcements/2020/06/01/cordova-ios-release-6.0.0.html
