### ISSUE TITLE
WKWebview Won't Load

### ISSUE THREAD

**Issue by albertleao** [apache/cordova-plugin-wkwebview-engine#60]
I receive the following error when I have wk webview installed:

`Failed to load resource: file:///var/containers/Bundle/Application/39F29CF9-4A2F-4A20-A296-0CAE487974B3/my.app/www/plugins/cordova-plugin-wkwebview-engine/src/www/ios/ios-wkwebview.js The requested URL was not found on this server.`

`Failed to load resource: file:///var/containers/Bundle/Application/39F29CF9-4A2F-4A20-A296-0CAE487974B3/my.app/www/plugins/cordova-plugin-wkwebview-engine/src/www/ios/ios-wkwebview-exec.js The requested URL was not found on this server.`

`Error: Module cordova-plugin-wkwebview-engine.ios-wkwebview-exec does not exist.`

I have the following in my config.xml

```
<feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
</feature>
<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
```

I noticed when I run cordova build ios, the 2 js files in the plugins folder get created, then deleted. Not sure why. Every other plugin is working fine.

**Comment by adadgio** [comment]
I had the same issue and solved it installing : cordova plugin add cordova-plugin-wkwebview-engine. Apparently this plugin needs to be installed for the fix to work.

Dont't forget to add ALL this in your config: 

<platform name="ios">
..........[other code]
        <feature name="CDVWKWebViewEngine">
            <param name="ios-package" value="CDVWKWebViewEngine" />
        </feature>
        <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
        <preference name="WKWebViewOnly" value="true" />
    </platform>

**Comment by breautek** [comment]
Closing, the solution is posted above.
