### ISSUE TITLE
iOS 12 DisallowOverscroll not working

### ISSUE THREAD

**Issue by slickjeep** [apache/cordova-plugin-wkwebview-engine#61]
The DisallowOverscroll preference doesn't disable bounce for all elements that scroll. Similar issue here https://github.com/ionic-team/ionic/issues/11844 where the elements glitch. The solution appears to be to disable all elements with overflow:scroll: https://github.com/ionic-team/ionic/issues/11844#issuecomment-391996908. Can anyone confirm this?

Thanks

**Comment by alexeybondarenko** [comment]
Hi. I have the same issue with Ionic@3.9.2. I've checked the logs of CDVWKWebViewEngine and looks like the value of DisallowOverscroll is passing down to the WebView controller. But it doesn't work as expected. 

Versions:
- Cordova 9.0.0 (cordova-lib@9.0.1)
- Ionic (Angular) 3.9.2

**Comment by spinninghamster** [comment]
Same issue here. Not working.

**Comment by Maxence-Machu** [comment]
You can fit it by disallowing overcroll directly in config.xml 

`<preference name="DisallowOverscroll" value="true" />`

I confirm the issue by the way.

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
