### ISSUE TITLE
iOS 12 and playing media fullscreen in WKWebView causes crash

### ISSUE THREAD

**Issue by dwolner** [apache/cordova-plugin-wkwebview-engine#63]
I am having a crashing issue in my iOS Cordova app that happens after going fullscreen in a video a couple times, much like these issues:
https://github.com/apache/cordova-plugin-inappbrowser/issues/298
https://github.com/youtube/youtube-ios-player-helper/issues/322 

I was hoping that by using WKWebView that the crashing issue I am experiencing in my app would be fixed, but it still persists, although it seems that WKWebView is somewhat more resilient and handles the crash more gracefully. XCode at least is now providing a response:

![wkwebview-issue2](https://user-images.githubusercontent.com/8670637/47403253-a6e69780-d6fd-11e8-8a2c-50361389fb4f.png)
![wkwebview-issue](https://user-images.githubusercontent.com/8670637/47403254-a6e69780-d6fd-11e8-9526-4dfe7401da71.png)

I know this is not a direct issue with the plugin, but is anyone else experiencing this problem or have work arounds? Is this a bug in iOS 12?

**Comment by JonathonDunford** [comment]
Bump. Experiencing same thing.

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
