### ISSUE TITLE
Layout abnormal under iPhone X+

### ISSUE THREAD

**Issue by Cui-y** [apache/cordova-plugin-wkwebview-engine#64]
### Description

After installing and using this plug-in, there is an abnormal phenomenon in iPhone X;  The bottom tab will move up.

IPhone 6,7,8 is Normal.

### Config
```xml
<feature name="CDVWKWebViewEngine">
      <param name="ios-package" value="CDVWKWebViewEngine" />
</feature>
<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
```

**Comment by janpio** [comment]
Can you provide a screenshot what is happening exactly?
What versions of everything are you using?
