### ISSUE TITLE
想问下这个插件怎么使用,

### ISSUE THREAD

**Issue by pengzhiqiang110** [apache/cordova-plugin-wkwebview-engine#65]
这个插件怎么用啊

**Comment by janpio** [comment]
It is all described in the README: https://github.com/apache/cordova-plugin-wkwebview-engine 
What problems are you having or what don't you know what to do?

**Comment by pengzhiqiang110** [comment]
我集成成功了 但是我把他集成到一个现成项目中,结果崩了,并且控制台没有什么有用信息.

**Comment by janpio** [comment]
Sorry, no idea about that. Stackoverflow is probably the better location to ask a question like that, or the Cordova Slack (slack.cordova.io).

I am going to close this now, feel free to open a new issue if you have a specific problem with this plugin. Thanks.

**Comment by pengzhiqiang110** [comment]
别关啊 
diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.这个问题遇到好多次了  总要给个解决方案吧
