### ISSUE TITLE
window.open won't work

### ISSUE THREAD

**Issue by mesqueeb** [apache/cordova-plugin-wkwebview-engine#72]
I'm not sure why but as soon as I install this plugin `window.open(url, '_blank')` and without _blank stops worknig.

I have this in my config.xml
```
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-navigation href="*" />
```

It works without the wkwebview plugin.

Related [open issue](https://issues.apache.org/jira/browse/CB-12228?jql=project%20%3D%20CB%20AND%20status%20%3D%20Open%20AND%20labels%20%3D%20wkwebview-known-issues) on apache issue tracker.

**Comment by janpio** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by CyberCyclone** [comment]
Same issue. It runs in the background as I can see the events firing, but the window isn't visible.

**Comment by noahcooper** [comment]
It appears `window.open` works if your app uses cordova-plugin-inappbrowser. However, as soon as that plugin is removed, window.open no longer has any effect. (I've recently removed cordova-plugin-inappbrowser from my app since it still uses the deprecated UIWebView.)

**Comment by MiguelQueiroz** [comment]
i used npm i @zestia/cordova-plugin-wkwebview-engine-windowopen  and it worked fine

**Comment by userException** [comment]
@MiguelQueiroz did you remove the already installed wkwebview before installing this ?

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
