### ISSUE TITLE
WKWebView - app over statusbar

### ISSUE THREAD

**Issue by LiveXenon** [apache/cordova-plugin-wkwebview-engine#73]
iPhone 6S iOS 12
<img width="415" alt="schermata 2019-01-13 alle 19 19 41" src="https://user-images.githubusercontent.com/34724827/51089112-41d49800-1768-11e9-8ee7-a8214bdc293e.png">
iPhone XS iOS 12
<img width="404" alt="schermata 2019-01-13 alle 22 35 30" src="https://user-images.githubusercontent.com/34724827/51090913-9a655e80-1783-11e9-877a-f57a6dd07a57.png">

I'm using cordova-plugin-wkwebview-engine development version and jQuery Mobile.
The app header remains above the status bar, I tried to use the statusbar plugin with overlaysWebView(false) but this seems to be developed for UIWebView. 

When imposed <preference name="StatusBarOverlaysWebView" value="false" /> the status bar starts correctly, then if I open an external link, or exit the app without closing it, it seems to lose the setting and overlaps. This also happens with iOS 9 and 11. iOS 10 I have not tested it.

Should I wait for the plugin plugin-plugin-statusbar update to fix this?

cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-labs-wkwebview-engine-localhost 0.5.1 "Cordova WKWebView Engine with http server (localhost) support"
cordova-labs-local-webserver 2.4.0 "CordovaLocalWebServer"
cordova-plugin-wkwebview-engine 1.1.5-dev "Cordova WKWebView Engine"

**Solution: the problem was caused by the plugin cordova-plugin-admob-free**

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
