### ISSUE TITLE
Canvas gets tainted when drawn with an image using the custom scheme

### ISSUE THREAD

**Issue by 5r1m** [apache/cordova-plugin-wkwebview-engine#79]
**Details:**
We are migrating from UIWebview to wkWebview for iOS, we got in to problem where Canvas gets tainted when loaded with an image using the custom scheme

**Problem**
For iOS, we are using setURLSchemeHandler to load the resources from Library folder. Resources (images, videos, pdfs etc) are loaded fine after doing necessary additions to meta tag to allow the new custom scheme being used. How ever canvas is getting tainted when we draw the image using the custom scheme and throws security CORS error when tried to get the canvas data using toDataURL.

I see error message "_SecurityError: The operation is insecure._" on call to toDataURL in console.

I know wkwebview is having issues( or strict) with CORS but as per document (https://cordova.apache.org/docs/en/latest/guide/appdev/whitelist/) this issue should not occur even for Canvas with _access origin='*'_ setting and custom scheme file loading, when its working fine for other elements.

**Note:** toDataURL works fine when Image element being drawn is set with base64 data instead of url with custom scheme

**Environment:**
iPad pro with iOS 12.1.3
cordova-plugin-wkwebview-engine : 1.1.4

Is this a bug in the cordova-plugin-wkwebview-engine?

**Comment by 5r1m** [comment]
We also tried with setting the crossorigin attribute to "anonymous" for the image being drawn on to canvas but this resulted in the below error even with _access origin='*'_:
_[Error] Origin null is not allowed by Access-Control-Allow-Origin.
[Error] Failed to load resource: Origin null is not allowed by Access-Control-Allow-Origin._

**Comment by rjurado01** [comment]
Same error, I have an image with this src: `"file:///var/containers/Bundle/Application/27131FF1-0862-4240-851F-FBDFFDDC47D4/HelloCordova.app/www/49dfd8c7f5effbcd57afcb1c060d6322.png"`

When I run this code:

```js
const image = document.getElementById("image");
var canvas = document.getElementById("canvas");
var ctx = canvas.getContext("2d");
ctx.drawImage(image, 0, 0);
```

I get this error: `SecurityError: The operation is insecure.` on call to `toDataURL`.

Using UIWebview this code works.

**Comment by jcesarmobile** [comment]
This plugin doesn't use custom scheme handlers, so I don't think the issue is caused by it.
