### ISSUE TITLE
Autofill not working correctly

### ISSUE THREAD

**Issue by mattwoberts** [apache/cordova-plugin-wkwebview-engine#80]
# Bug Report

I'm not 100% sure if this is a bug with the cordova plugin, the WKWebView itself, or just cordova in general, but I think it makes the most sense to report here.

## Problem

On iOS (12.1.4), using the default keychain password manager, when I hit the login page for a hosted web app, I am prompted to login with a stored password. I click the suggest password from the keyboard, and nothing happens - the fields are not filled in. If however I click the key icon, and choose a username/password from the list, these are indeed filled in on the page. 

If I change to a different password manager - such as 1password - the problem goes away.

if I try logging in to the hosted web app "normally" in safari on my mobile instead, it works correctly there too.

### Version information
I'm on the latest WKWebView plugin. (1.1.4). I'm on 4.5.5 of the cordova-ios platform, but I have also tried upgrading to 5.0.0, which doesn't make any difference.
Cordova version 8.0.0

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by shogoland** [comment]
I have same issue, too.
However,  I got correcly working on iPhoneX.

**Comment by michielcrabbe96** [comment]
> I have same issue, too.
> However, I got correctly working on iPhoneX.

Do you know how you got it working on iPhoneX? I can't even get password suggestions...

**Comment by sjoerdloeve** [comment]
Facing with the same issue.

I did already:
- enable the AutoFill Credential Provider
- add the Associated Domains and add webcredentials key
- setup apple-app-site-association file

Not only passwords are not working, also name and address field won't auto-fill with wkwebview

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
