### ISSUE TITLE
Getting white screen(IOS App) after using the app for around 5 minutes.

### ISSUE THREAD

**Issue by SuryaAcube** [apache/cordova-plugin-wkwebview-engine#82]
# Bug Report
When we are navigating(routing)  between the  pages continuously , suddenly we are getting white screen. 
## Problem
Getting white screen
**Console Error  from x-code** : Error Route:  InvalidStateError: The object is in an invalid state.
### What is expected to happen?
When we click on the any button which is suppose to redirect to other page, It is showing whitescreen instead of the actual page it should navigate(show).

### What does actually happen?
Got white screen while navigating inside the app.

### Environment, Platform, Device

IOS, Mobile App, Iphone 6s

### Version information

We are generating the build from build.phonegap.com

Here is config which we are using : 
```
<plugin name="cordova-plugin-wkwebview-engine"/>
<plugin name="cordova-plugin-wkwebviewxhrfix" spec="https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix" />
<feature name="CDVWKWebViewEngine">
      <param name="ios-package" value="CDVWKWebViewEngine" />
 </feature>
 <access origin="http://localhost:8080/*" />
 <allow-navigation href="http://localhost:8080/*" />
 <allow-navigation href="*" />
 <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
 <preference name="ScrollEnabled" value="true" />
```
## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by jcesarmobile** [comment]
Can’t reproduce and the requested information was not provided, so closing.
Feel free to reopen or create a new issue if you can provide the requested information
