### ISSUE TITLE
(iOS) Infinite Loop when a "NSURLErrorCancelled -999" is received on didFailLoadWithError

### ISSUE THREAD

**Issue by gwynjudd** [apache/cordova-plugin-wkwebview-engine#83]
# Bug Report
Basically identical to the issue described in https://github.com/apache/cordova-ios/pull/334, but for WKWebView.

If you cancel navigation in shouldOverrideLoadWithRequest in a plugin, and then do `[webViewEngine loadRequest...]` to load something else, if you get the timing just right, it will go into an infinite loop in `didFailNavigation`.

## Problem
Infinite loop in `didFailNavigation`.

### What is expected to happen?
Should not infinite loop.

### What does actually happen?

Infinite loop with failed loads of the error URL.

## Information

PR should be forthcoming that basically copies this https://github.com/apache/cordova-ios/pull/334. I'll link it to this when I submit it.

### Command or Code
As described. It seemed to depend a bit on timing, so I can't easily provide a code sample that consistently replicated the issue.

### Environment, Platform, Device

Various different iOS devices and simulators.

### Version information

cordova-plugin-wkwebview-engine - 1.1.4

## Checklist

- [ x ] I searched for existing GitHub issues
- [ x ] I updated all Cordova tooling to most recent version
- [ x ] I included all the necessary information above

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
