### ISSUE TITLE
this class is not key value coding-compliant for the key _alwaysRunsAtForegroundPriority.

### ISSUE THREAD

**Issue by chavesgu** [apache/cordova-plugin-wkwebview-engine#85]
# Bug Report

## Problem
Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<WKWebViewConfiguration 0x117e17320> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key _alwaysRunsAtForegroundPriority.'
### What is expected to happen?
app work normal

### What does actually happen?
this problem cause app can't work

## Information

when i run this plugin in ios@12.2 & xcode@10.2

### Command or Code

run this plugin in ios@12.2 & xcode@10.2

### Environment, Platform, Device

ios 12.2

### Version information

cordova-plugin-wkwebview-engine @ 1.1.4
cordova-ios@4.5.5
cordova@8.0.0

## Checklist

- [ x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by janpio** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by jcesarmobile** [comment]
This plugin doesn’t include _alwaysRunsAtForegroundPriority, so it’s caused by another plugin. Check background plugins you are using, one of them is probably the cause.
