### ISSUE TITLE
Keyboard not showing on  focus for IOS 12.2

### ISSUE THREAD

**Issue by oaguinaga** [apache/cordova-plugin-wkwebview-engine#86]
# Bug Report

## Problem
Whit the new release of IOS 12.2 there seems to be an issue when focusing, the keyboard does not seem to show.

Here is a [link](https://stackoverflow.com/questions/32449870/programmatically-focus-on-a-form-in-a-webview-wkwebview/55344531#55344531) to stackoverflow question regarding this problem:

### What is expected to happen?

Keyboard should show when focusing an element. ie:

`document.querySelector('input').focus()`

### What does actually happen?

Keyboard does not show when focusing on an input element. 

### Environment, Platform, Device

IOS 12.2

## Checklist

- [ ✅] I searched for existing GitHub issues
- [ ✅] I updated all Cordova tooling to most recent version
- [ ✅] I included all the necessary information above

**Comment by DavidBriglio** [comment]
I have found this plugin to fix the issue: https://www.npmjs.com/package/cordova-plugin-wkwebview-inputfocusfix

At least as a stopgap while this does get fixed.

**Comment by benmcmaster** [comment]
The fix above was working great... But then iOS 13 happened. Is anyone else seeing this issue again in iOS 13? Also the plugin: https://www.npmjs.com/package/cordova-plugin-wkwebview-inputfocusfix has been deprecated based on merged changes...

**Comment by spinninghamster** [comment]
> The fix above was working great... But then iOS 13 happened. Is anyone else seeing this issue again in iOS 13? Also the plugin: https://www.npmjs.com/package/cordova-plugin-wkwebview-inputfocusfix has been deprecated based on merged changes...

Is the problem happening again in iOS 13?

**Comment by Drewm95** [comment]
We are experiencing this issue on iOS13.1.2, Cordova 9.0.0, iOS platform 5.0.0. In our testing the plugin mentioned above works for devices prior to iOS13 but not after.

**Comment by Drewm95** [comment]
This fix worked for us https://github.com/ionic-team/cordova-plugin-ionic-webview/commit/7a514b071ba2c094e02f56f46f2e90a2a3a1e9be

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
