### ISSUE TITLE
Does this plugin still work?

### ISSUE THREAD

**Issue by p3v9d5ui** [apache/cordova-plugin-wkwebview-engine#88]
I've added this plugin to my Cordova project for iOS, but it seems to have no effect. Is it it still working with the latest iOS version/Xcode, etc?

I have verified that the plugin in installed in my config.xml file:

`<plugin name="cordova-plugin-wkwebview-engine" spec="^1.1.4" />`

And also that these directives are installed:

`
<feature name="CDVWKWebViewEngine">
    <param name="ios-package" value="CDVWKWebViewEngine" />
</feature>
<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
`

But, when I recompile and install on my iPhone 6s, I get this in the log:

`Using UIWebView`

Any ideas?

This is my setup:

Plugin: 1.1.4
Cordova: 8.1.2 (cordova-lib@8.1.1)
Xcode: 10.1
iOS 12.1.4

**Comment by victor1342** [comment]
I've got it working with a similar setup. I think you need to remove and re-add the platform:
```
cordova platform rm ios
cordova platform add ios
```

**Comment by p3v9d5ui** [comment]
Thanks @victor1342 ! That at least moved things forward. Now, however, I get this error on startug:

> 2019-04-11 10:01:35.137283+0200 hileadzz[9463:11123455] [DYMTLInitPlatform] platform initialization successful
2019-04-11 10:01:35.246345+0200 hileadzz[9463:11123318] Apache Cordova native platform version 4.5.5 is starting.
2019-04-11 10:01:35.247113+0200 hileadzz[9463:11123318] Multi-tasking -> Device: YES, App: YES
2019-04-11 10:01:35.252567+0200 hileadzz[9463:11123318] -[__NSDictionaryM cordovaSettingForKey:]: unrecognized selector sent to instance 0x2820c8400
2019-04-11 10:01:35.253295+0200 hileadzz[9463:11123318] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryM cordovaSettingForKey:]: unrecognized selector sent to instance 0x2820c8400'
*** First throw call stack:
(0x1ea355ea4 0x1e9525a50 0x1ea26eb14 0x1ea35b7bc 0x1ea35d46c 0x102804980 0x1026d6dc8 0x216f2d890 0x216f2dcc0 0x21752c128 0x21752c6d0 0x21753d6d8 0x10280915c 0x1026d6ae4 0x2174ebca0 0x2174ed408 0x2174f2e54 0x216d8e93c 0x216d975bc 0x216d8e5b8 0x216d8ef58 0x216d8d058 0x216d8cd04 0x216d91ec4 0x216d92e24 0x216d91d7c 0x216d96c68 0x2174f134c 0x2170dc244 0x1ecd8c9d4 0x1ecd9779c 0x1ecd96e94 0x1034e4dc8 0x1034e8a10 0x1ecdcba9c 0x1ecdcb728 0x1ecdcbd44 0x1ea2e60e0 0x1ea2e6060 0x1ea2e5944 0x1ea2e0810 0x1ea2e00e0 0x1ec559584 0x2174f4c00 0x1026d69dc 0x1e9d9ebb4)
libc++abi.dylib: terminating with uncaught exception of type NSException

I'll open a new issue for this.

**Comment by victor1342** [comment]
From the error message I can see that you're on version 4.5.5 of the cordova iOS platform, try upgrading to the latest one (5.0.0)

**Comment by p3v9d5ui** [comment]
Thanks again @victor1342 ! This was exactly right, and it works now.
