### ISSUE TITLE
Issue waking app and running JS in background from VOIP notification

### ISSUE THREAD

**Issue by tbassett44** [apache/cordova-plugin-wkwebview-engine#89]
I have an app the requires silent notifications and it seems impossible to do this as of now with wkwebview and I am curious if it will ever be.  With WkWebview, it seems that starting an app from a killed state does not work.  Will this ever be available?  Or is this an inherent issue with WkWebview needing to run on the main UI thread?  If that is the issue, will it be possible for there to be a JSContext bridge that allows loading all the plugins JS apis to be made available "headless" with a custom file that can be declared for handling logic.

Everything works great with UiWebView, my app properly starts in the background if not already running and successfully loads the view and runs any javascript necessary.  But I cant use UiWebView because of performance issues when there are multiple videos on a page in my app.

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
