### ISSUE TITLE
Clarify iOS version requirement for wkwebview-engine plugin

### ISSUE THREAD

**Issue by dsmithhfx** [apache/cordova-plugin-wkwebview-engine#95]
-

**Comment by dsmithhfx** [comment]
Hi,

The plugin docs state, "installable only on a system with the iOS 9.0 SDK". Does this mean iOS 9.0 _and newer_, or that the SDK must be present in XC, and the cordova ios app built against that target (e.g. "cordova build ios --target"iPad blah blah, 9.0"?

I tried tried build against a 12.1 target, and the app failed to open a webview in the xc simulator.

Thanks for any clarification!

**Comment by jeeva-nikam** [comment]
I am also facing this issue.
Application is installed but not able to see the first screen of app i.e. login screen.
I am using Angularjs in that <div ng-view></div> is not loading the default login page route.
App is loading the index.html only problem with routing.

**Comment by breautek** [comment]
It means at minimum, you need the iOS 9 SDK installed in xcode. It doesn't define the minimum version of iOS.

Do note that Apple forces you to install/build with specific certain sdk versions, so you should always use the latest release when available.
