### ISSUE TITLE
Calling history.go(-3) goes back only one time

### ISSUE THREAD

**Issue by 349989153** [apache/cordova-plugin-wkwebview-engine#96]
# Bug Report

## Problem
On iOS devices we have `page A -> page B -> page C -> page D`, and in the `page D` we are calling `history.go(-3)`.

### What is expected to happen?
go back to the `page A`

### What does actually happen?
go back to the `page C`. 

And the same js code works perfect on Android devices.

### Environment, Platform, Device

Platform: iOS, xcode 10.2.1

Device: iPhone simulator or the real iPhone, iOS 12.2

### Version information

cordova: 8.0.0
cordova-ios: 4.5.4
cordova-plugin-wkwebview-engine: 1.1.4
iOS: 12.2
xcode: 10.2.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
