### ISSUE TITLE
WKWebView doesn't react on clicks (iframe) while UIWebView does - iOS

### ISSUE THREAD

**Issue by bozzzi** [apache/cordova-plugin-wkwebview-engine#98]
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [x] Support Question

## Description
WKWebView doesn't react on clicks (iframe) while UIWebView does
Similar question:
https://stackoverflow.com/questions/51175746/wkwebview-doesnt-react-on-clicks-while-uiwebview-does?answertab=oldest#tab-top

## Information

Steps to reproduce:

1. Create new cordova project
2. Test it on UIWebView - It's working
3. Test it on WKWebView - not working

### Command or Code

```
cordova create hello com.example.hello HelloWorld
cd HelloWorld
cordova platform add ios
```
Open project in Xcode and change **receivedEvent**: function from index.html file accordingly
(Just adding simple DFP add - js api)
```
receivedEvent: function(id) {
                googletag.cmd.push(function() {
			googletag.defineSlot('/271507443/patuljak-aplikacija-b2', 
			[300, 250],
			'here').addService(googletag.pubads()).setCollapseEmptyDiv(true);
			
			googletag.pubads().enableSingleRequest();
			googletag.enableServices();
			googletag.display('here');
		});
}
```
create empty div in body of index.html file
```
<div id="here"></div>
```

Add to head of index.html file

```
<script async='async' src='https://www.googletagservices.com/tag/js/gpt.js'></script>
  <script>
  	var googletag = googletag || {};
  	googletag.cmd = googletag.cmd || [];
  </script>
```

Run project in xcode... Everything **should be running fine in UIWebView.**

Now, add WKWebView plugin
```
cordova plugin add cordova-plugin-wkwebview-engine
```
After successful installation, you should have, inside config.xml file:
```
<feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>
    <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" /> 
```
Run project again, **it is not possible to click on add in WKWebView**

If wkwebview plugin removed everything works fine again.
Working OK in browser too.

### Version information
- 9.0.0 (cordova-lib@9.0.1)
- Mac OS High Sierra 10.13.6 (17G65)
- Xcode Version 10.1 (10B61)
- iPhone XS, iPhone 5SE, iPhone 6S

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by ahmadwaliesipick** [comment]
facing same issue did you find any solution?

**Comment by phiasco12** [comment]
same issue here... any solution to this... I'm just using normal:

```
$(document).on('click','element',function(e){
.....

});
```

**Comment by bozzzi** [comment]
try this

[Fix](https://github.com/bozzzi/wkwebClickFix)

**Comment by fukemy** [comment]
> try this
> 
> [Fix](https://github.com/bozzzi/wkwebClickFix)

hi, can you tell me how to fix? Im using CDVViewController then got the same above error

**Comment by touficy** [comment]
> facing same issue did you find any solution?

hi ahmad
did you find solution for this issue

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
