### ISSUE TITLE
Missing keywords for integrating with plugin search

### ISSUE THREAD

**Issue by feiandytan** [apache/cordova-plugin-wkwebview-engine#99]
# Bug Report

## Problem
Missing keywords "ecosystem:cordova" in package.json. This plugin cannot be searched out on Cordova Plugin Search: https://cordova.apache.org/plugins/?q=cordova-plugin-wkwebview-engine&platforms=cordova-ios

### What is expected to happen?
Open the url: https://cordova.apache.org/plugins/?q=cordova-plugin-wkwebview-engine&platforms=cordova-ios
The plugin "cordova-plugin-wkwebview-engine" should be found.

### What does actually happen?
Cordova Plugin Search cannot find this plugin.

## Information

According to Cordova documentation: https://cordova.apache.org/docs/en/latest/guide/hybrid/plugins/index.html#integrating-with-plugin-search
The keywords "ecosystem:cordova" is required for integrating with Plugin Search.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
Would love to merge a PR adding this.
